### ISSUE TITLE
Properly avoid auth rate limiting in SkypeEventLoop

### ISSUE THREAD

**Issue by Richie94** [Terrance/SkPy#103]
Hey there,
I want to know, how I can avoid getting auth rate limited so fast. I use the SkypeEventLoop and that seemed to work for some time without problems, but right now I'm getting auth rate limited right after sending first message. Therefore i want to know, if that token handling all works automatically in background or if I have to do something myself to let this work.
Right now my RaspiBot cant really work...

Thanks,
Richard

**Comment by Terrance** [comment]
Tokens are refreshed when needed, but that has nothing to do with rate limiting.  You didn't post your code so I don't know what or how you're sending, but if this is a new account trying to just send out then it's fairly likely to be flagged as spam and limited.  Multiple logins in a short space of time will also get you limited.  Best thing to do is to log in to Skype for Web and check if you can send over there.

**Comment by Richie94** [comment]
I didnt posted code because i just referred to the normal __init__ methode with user, password and tokenfile. Logging in via Web works and there are no problems, but i have to mention, that i can do this just for different IP address because my Raspi where the script is executed works without desktop...

The problem started with no reaction, so that the system seemed to freeze but since a few days i get that auth rate limit very quick...

Do you know, if that limiting policy is less restrictive if i just wait a few days?

**Comment by Terrance** [comment]
IP will likely be affecting it -- proxy over SSH (e.g. SOCKS with `ssh -D`) or otherwise to complete a browser session via the Pi's network connection and IP.

**Comment by Richie94** [comment]
nice idea, tried logging in and no problems there. but again after loggig in via skpy right after first send
 'StatusText': 'Login Rate limit exceeded'                                                                                                                                             
{'errorCode': 803, 'message': 'Login Rate limit exceeded'}

**Comment by Richie94** [comment]
do you have any experience with e.g. https://github.com/denissa4/skype_chatbot or in general with some kind of authetication that you are a bot? i think maybe the problem is this missing authentication?!
Or do you have such an EventLoop which is running w/o problems 24/7?

**Comment by Terrance** [comment]
I haven't used the Bot SDK, no.  If you're intending to build a bot, it would be preferable to use the official SDK over this library (which emulates a client for human users).

As of last time I tested, sessions only last 24 hours.  If you provide a `Skype` instance with a username and password, it will reconnect when the session expires using those credentials, so yes, you can have a loop running full-time.

**Comment by Richie94** [comment]
Okay, seems some 'feature' I implemented lead to quick auth rate.
```while True: 
    p = multiprocessing.Process(target=evl.cycle)
    p.start()
    time.sleep(1)
    p.join(600)
    if p.is_alive():
	    logging.error("Task not finished after 600s, terminate")
    	    p.terminate()```
I did this because the process seemed to freeze after around that 24h +/-
Lets see if this freezing was just temporary or not but i still dont know why multiprocessing lead to auth rate exceeding...

**Comment by Richie94** [comment]
As an experiment, i wanted to see where it hangs, so every 500 runs it should print out "Still alive"
```
	def loop(self):
		self.counter = 0
		while True:
			self.cycle()
			self.counter += 1
			if self.counter % 500 == 0:
				logging.info("Still alive")
```

What i got out was:
```
2019-01-31 19:04:13,593 INFO Still alive
2019-02-01 00:11:53,384 INFO Still alive
```
So i started it at 19.04 and it took over 5 hours until it ran 500 times? Does that mean the polling slows somewhere down daramatically? Because now 17 hours later I still got no 3rd still alive signal. For me it seems that after some time it gets stuck in fetching events and therefore the whole system does not work...

**Comment by Terrance** [comment]
Unless you've got a busy Skype account with many contacts, you're unlikely to get that many events come through.  An event might be a status change, an incoming/outgoing message or a typing notification, so you can get a rough idea of how many events you might expect.

Instead of overriding `loop()` and logging every 500th event, why not just implement `onEvent()`?  Print out each event (use `repr(event)` for a more compact display), then you'll have some actual insight into the flow of events.
