### ISSUE TITLE
Support for the current version of Skype for Web is ending.

### ISSUE THREAD

**Issue by Ashymad** [Terrance/SkPy#105]
![image](https://user-images.githubusercontent.com/15618637/51802708-ed8fe480-224c-11e9-8e8f-989da1ad15bb.png)

This banner is being shown in the Skype for Web UI since a few weeks ago.
There does not seem to by any official info when will the old version be taken down.
The [new app](https://preview.web.skype.com) does not seem to use the same APIs as the old one, so if the old APIs are shut down SkPy will stop working.

**Comment by Terrance** [comment]
At a quick first glance:

* Microsoft auth remains unchanged.
* Initial handshake has been simplified -- no more lock-and-key or endpoint registration.
* Messages are now sent and received via websocket -- no more long-polling (which probably explains the lack of endpoints).

**Comment by metasonic** [comment]
@Terrance is there anything we can do to help integrate the new API's into the app? I'm not sure I have the necessary knowledge to write the code but would gladly help with anything that you think may be useful.

**Comment by Terrance** [comment]
Rewriting for websockets is a fairly significant undertaking, though it looks like the request format is a crude representation of the existing HTTP requests against the gateway API so it might be translatable.  In the first instance, it would be useful to inspect this in detail and confirm if the requests are of the same format.

More generally, the rewrite proposal in #78 still stands, but my interest in doing so dwindles -- I haven't used Skype in personal capacity for well over a year now.  An asyncio-based library would improve working with websockets (both `aiohttp` and `websockets` provide neat support) and an event loop as a whole.

**Comment by Terrance** [comment]
Looks like the preview has ended and is now the default version.  Old APIs are still functional at present.

**Comment by EgorDenisenko** [comment]
Hello, today I will try exec my micro project and I always catch next exception:
('400 response from POST https://neudb5-client-s.gateway.messenger.live.com/v1/threads', <Response [400]>)
Login was successful.
Are you sure that it still alive?
Because 2 month ago this code work properly.

**Comment by Terrance** [comment]
The POST failure you're seeing appears to be coming from creation of a new group chat, which admittedly I hadn't tested -- it's possible the endpoint for that has changed.  How do the underlying requests for that look in the new Skype for Web?

**Comment by EgorDenisenko** [comment]
Yes, it's request for creating group chat between 3 users.
So if API request doesn't changed, what could be a reason to 400 response? I tested it for different skype accounts ( from AWS and from local machine too ) and with different users. I had Response 400 always.

**Comment by Richie94** [comment]
Is it still working? Since a few days I only get these two errors and cant login
```
skpy.core.SkypeAuthException: ("Couldn't retrieve t field from login response", <Response [200]>) 
skpy.core.SkypeAuthException: Token file has expired
```

**Comment by Terrance** [comment]
@Richie94 Still working, see #65 for options (namely, log into web.skype.com in a browser, you're probably hitting a roadblock page asking for verification).

**Comment by Richie94** [comment]
still not able to login. tried multiple computers, nowhere i was able to get some results, everywhere same error...

**Comment by meloman-a** [comment]
There is response like
`<html>
   <head>
      <noscript>
         JavaScript required to sign in
         <meta http-equiv="Refresh" content="0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=e70fcf631e804c5aafed243654adad7d&client_flight=ReservedFlight33,ReservedFligh"/>
      </noscript>
      <title>Continue</title>
      <script type="text/javascript">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script>
   </head>
   <body onload="javascript:DoSubmit();">
      <form name="fmHF" id="fmHF" action="https://account.live.com/identity/confirm?mkt=EN-US&uiflavor=web&id=293290&ru=https://login.live.com/login.srf%3fid%3d293290%26opid%3dCD3C9619C22758FD%26opidt%3d1555313586" method="post" target="_top"><input type="hidden" name="client_flight" id="client_flight" value="ReservedFlight33,ReservedFligh"><input type="hidden" name="ipt" id="ipt" value="DVZ8EqgCkamDtB0xjvFvfmEX81bIyewhJlBRIVekkS4vLOW!gOkB7CxE*ufuRXrYmOc26T!RXHVMkScL*md0KhzPL86RGn4VnIvbYSeLRV!naDs10dd1ZS9qcokgxLwdH9SLLQXxbU12A1qMAiLUpOw1av3jsbEIn789MS74NXboC!tnYuwBDf3nJjKiAjYMCLKSXpLtfo42iQkdD!Tzc22Jus4BTYrUjfdXr023!Ty7zr5lXXtGq5qw8OWQR!yPviVkPdvWjavjf2vviMShZdn!HYfc*MbvZSJHNe7GOmCZcOiujucJDgKPv4GELA6YypFPyOladkWnZF8q1uWtQTBA53qmkF56AcT0EltrB0YoKYvknEvjT8*gaJrUGwPrYws5VFkhdX*OZ*ldMmsMnkZZUEMuSC76RRxILA9nRMkD8E67axQmNs3*6Em4n2!pHoepWNfMWTV2d80HvJNIVZOl5Y9aPeLyk6jFgWV65sda"><input type="hidden" name="pprid" id="pprid" value="f2a39c42dab816ff"><input type="hidden" name="uaid" id="uaid" value="e70fcf631e804c5aafed243654adad7d"></form>
   </body>
</html>`
After POST command in "sendCreds" function.

**Comment by meloman-a** [comment]
Maybe you need handle confirm challenge in https://account.microsoft.com, just try autenticate there before.

**Comment by flannan-h** [comment]
> ... so if the old APIs are shut down SkPy will stop working.

any chance this took place sometime over the weekend?

connection issues across several machines today:

`ConnectionError: HTTPSConnectionPool(host='flagsapi.skype.com', port=443): Max retries exceeded with url: /flags/v1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002006CBC4C50>: Failed to establish a new connection: [WinError 10060]....`

**Comment by Richie94** [comment]
> > ... so if the old APIs are shut down SkPy will stop working.
> 
> any chance this took place sometime over the weekend?
> 
> connection issues across several machines today:
> 
> `ConnectionError: HTTPSConnectionPool(host='flagsapi.skype.com', port=443): Max retries exceeded with url: /flags/v1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002006CBC4C50>: Failed to establish a new connection: [WinError 10060]....`

Same here, guess you are right...

**Comment by Ashymad** [comment]
@flannan-h @Richie94 Flags API removal (https://github.com/Terrance/SkPy/issues/113) was just fixed in v0.9.1

**Comment by snitkoff** [comment]
> Messages are now sent and received via websocket

@Terrance tell me, please, where can I find documentation on working with web sockets? It seems that Microsoft wants to transfer everyone to BotFramework and all the documentation applies only to it :)

**Comment by Terrance** [comment]
There is none, Skype for Web's internal APIs are private and undocumented.  Bot Framework is the official solution to integrating with Skype.

**Comment by Terrance** [comment]
As nothing really seems to have changed since that banner appeared, I'm going to go ahead and close this.
