### ISSUE TITLE
setAvatar problem

### ISSUE THREAD

**Issue by verybasicneeds** [Terrance/SkPy#106]
Hello,

i am having an issue to get setAvatar working.

(but for example, setMood is working)

Account is a Microsoft one ("live:")

I get a 404 error, if i use this code : 

`# -*- coding: utf-8 -*-

from skpy import Skype

import sys

import time

import os

sk = Skype(tokenFile="c:/token.txt")

sk.setAvatar(open("c:/image.jpg","rb"))
`

I tried to fix it on my own, i went into the firefox inspector, and see that it uses somethings like https://avatar.skype.com/v1/avatars/userid now (it's still a PUT).

I added a API_AVATAR line with https://avatar.skype.com in conn.py and i modified the setAvatar in main.py with this:

`self.conn("PUT", "{0}/v1/avatars/{1}".format(SkypeConnection.API_AVATAR, self.userId),
                  auth=SkypeConnection.Auth.SkypeToken, data=image.read())`

But now instead of the 404 response, i got a 400 response..

Any help appreciated :)

**Comment by verybasicneeds** [comment]
Hello,

I found the problem for the 400 error.

The problem is because of the Content-Type that had to been set with : image/jpeg

If you need setAvatar working, it needs two modifications :

First adding this line to conn.py : 

    API_AVATAR = "https://avatar.skype.com"

Secondly, editing the setAvatar in main.py : 

customheader = {'Content-type': 'image/jpeg'}
self.conn("PUT", "{0}/v1/avatars/{1}".format(SkypeConnection.API_AVATAR, self.userId),
                  auth=SkypeConnection.Auth.SkypeToken, data=image.read(), headers = customheader)

Then it works (for jpg files at least)

Otherwise i would like to thank Terrance for this really good project

**Comment by Terrance** [comment]
Setting the Content-Type to image/png doesn't seem to work at all:

> 40003: Request format is invalid.

Sending a PNG with a Content-Type of image/jpeg is rejected too:

> 40054: The data you are trying to upload is not valid image.

Choosing a PNG in Skype for Web appears to upload a JPEG in all cases (check the request payload in DevTools, you should be able to see something like `ÿØÿà` and `JFIF` towards the start) -- is there some client-side image conversion going on?  No additional API calls before the upload.

If only JPEGs are supported then conversion is out of scope, but other libraries exist for that if needed.

**Comment by verybasicneeds** [comment]
Okay thank you.

To be honnest, i didn't tested any other image format because JPEG was ok for me at the moment during my tests, but yes, eventually if someone needs to set as avatar different image format then it should possible to add some lib like Pillow.

**Comment by bofortitude** [comment]
Hi there, thanks for you guys trying, thanks for Terrance's nice work! But I need to set the Skype group avatar, it looks like not working, do you have any ideas for that?

**Comment by Terrance** [comment]
The endpoint for uploading avatars has changed in the meantime, and the new one appears to cope with PNGs whilst sending a fixed JPEG content-type header.
