### ISSUE TITLE
Response 400 from attempt to message group chat

### ISSUE THREAD

**Issue by anhuntz** [Terrance/SkPy#108]
I'm trying to schedule messages to send in a group thread I'm in with some other users. My code is shown below, but I can't find in the documentation if this is even how it's properly done.

`
from skpy import Skype, SkypeChats
SKPY_DEBUG_HTTP=1
sk = Skype('user', 'password')

ch = sk.contacts.contact("19:f19aab2.....e10dd@thread.skype").chat

ch.sendMsg('message')
`

After running, I get an HTTP response 400. Any ideas?

**Comment by anhuntz** [comment]
ah. figured it out. 
Should be"
ch = sk.chats.chat("19:f19aab2.......e10dd@thread.skype")
"

**Comment by Terrance** [comment]
From the [`SkypeChats`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChats) docs:

> Key lookups allow retrieving conversations by identifier.

Therefore you should actually be doing:

```python
 ch = sk.chats["19:f19aab2.......e10dd@thread.skype"]
```

Calling `SkypeChats.chat()` will make a network request each time to retrieve it, whereas key lookups will used a cached copy if available (and fall back to the former call when not yet cached).
