### ISSUE TITLE
Send msg to group

### ISSUE THREAD

**Issue by Cubillosxy** [Terrance/SkPy#110]
### Question

I want to send msg to exist group. 

`sk.groups['mygroup'].chat`

some example for that?

**Comment by Terrance** [comment]
Groups are just named collections of contacts to organise your contact list.  If you mean a group conversation (with an ID like `19:a1b2c3...d4e5f6@thread.skype`), you need to [access it from `sk.chats`](https://skpy.t.allofti.me/usage.html#using-conversations).

**Comment by Cubillosxy** [comment]
@Terrance ,  I mean a group conversation that already exist not  just created. when I type 

> sk.chats # I get current chats , 

but in my entire `sk.contacts ` I don't have my groups (groups where I am a member )

**Comment by Terrance** [comment]
I don't understand what you're asking for.  `sk.chats["19:a1b2c3...d4e5f6@thread.skype"]` using a real ID will give you the corresponding group chat.  Contacts is a list of users, not chats -- both one-to-one and group conversations can be found in `sk.chats`.

**Comment by Cubillosxy** [comment]
I mean, I'm a member of a  group ("spk-"), I want to send messages to that group.

**Comment by Terrance** [comment]
Not seen an `spk` prefix before, can you elaborate?  Where is that in Skype for Web's UI?

Only thing I can find is [Skype Private Conversations](https://support.skype.com/en/faq/FA34824/what-are-skype-private-conversations), which I assume you're not referring to as they're only one-to-one chats (in any case, SkPy doesn't provide methods to create them, and existing ones likely won't show up if they need client-local encryption keys).

**Comment by Cubillosxy** [comment]
I can send message to my group conversation  ( `sk.chats["id"] `) , but I get the ID thanks to [SkypeEventLoop](https://pypi.org/project/SkPy/#SkypeEventLoop). (wait for new messages in my group) 

But I need other way for get my group conversation ID. 
thanks .

**Comment by Terrance** [comment]
You'll have to check [`sk.recent()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChats.recent) -- it'll return a page at a time, so for a complete list you'll need to keep calling it until it returns empty.

**Comment by Cubillosxy** [comment]
`sk.chats.recent() ` works .  

Thanks.
