### ISSUE TITLE
I send a real delete message. 

### ISSUE THREAD

**Issue by a97077088** [Terrance/SkPy#112]
I send a real delete message. After calling getmsg several times, the message appears repeatedly. Can implement the delete interface?

**Comment by Terrance** [comment]
There is no "real" delete -- messages remain in the API history, only the clients hide them.

**Comment by a97077088** [comment]
It seems that the client can really delete the message. I'll analyze the package.

DELETE /v1/users/ME/conversations/8%3Alive%3A.cid.bf51620611ccc565/messages/1570459529455 HTTP/1.1
Host: client-s.gateway.messenger.live.com
behavioroverride: redirectAs404
registrationtoken: registrationToken=U2lnbmF0dXJlOjI6Mjg6QVFRQUFBQnQwa09RQzNPTGNoKyt6U3lweDFwYjtWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDg3NDY2MDExNzg0NzMzMzk7RXAuSWRUeXBlOjc6MTo4O0VwLklkOjI6MjY6bGl2ZTouY2lkLjc4MTI2NzJjNzM4MWQ0ODc7RXAuRXBpZDo1OjM2OmE3YzQ2MzhhLWJlOTgtMmYyMy1iZTk4LTQyYzY0MmM2YmU5ODtFcC5Mb2dpblRpbWU6NzoxOjA7RXAuQXV0aFRpbWU6NDoxOTo1MjQ4NzQ2NjAxMTY3NjkyNDM5O0VwLkF1dGhUeXBlOjc6MjoxNTtFcC5FeHBUaW1lOjQ6MTk6NTI0ODc0NzIyODc1NzM4NzkwNDtVc3IuTmV0TWFzazoxMToxOjI7VXNyLlhmckNudDo2OjE6MDtVc3IuUmRyY3RGbGc6MjowOjtVc3IuRXhwSWQ6OToxOjA7VXNyLkV4cElkTGFzdExvZzo0OjE6MDtVc2VyLkF0aEN0eHQ6Mjo0NDQ6Q2xOcmVYQmxWRzlyWlc0YWJHbDJaVG91WTJsa0xqYzRNVEkyTnpKak56TTRNV1EwT0RjQkExVnBZeFF4THpFdk1EQXdNU0F4TWpvd01Eb3dNQ0JCVFF4T2IzUlRjR1ZqYVdacFpXU0gxSUZ6TEdjU2VBQUFBQUFBQUVBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBYWJHbDJaVG91WTJsa0xqYzRNVEkyTnpKak56TTRNV1EwT0RjQUFBQUFBQUFBQUFBSFRtOVRZMjl5WlFBQUFBQUVBQUFBQUFBQUFBQUFBQUNIMUlGekxHY1NlQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBUnBzYVhabE9pNWphV1F1TnpneE1qWTNNbU0zTXpneFpEUTROd0FBQUFBQXlmcWFYUWNBQUFBSVNXUmxiblJwZEhrT1NXUmxiblJwZEhsVmNHUmhkR1VJUTI5dWRHRmpkSE1PUTI5dWRHRmpkSE5WY0dSaGRHVUlRMjl0YldWeVkyVU5RMjl0YlhWdWFXTmhkR2x2YmhWRGIyMXRkVzVwWTJGMGFXOXVVbVZoWkU5dWJIa0FBQT09Ow==; expires=1570524233; endpointId={a7c4638a-be98-2f23-be98-42c642c6be98}
clientinfo: os=iOS; osVer=12.4; proc=x86; lcid=zh-CN; deviceType=2; country=CN; clientName=skype4life; clientVer=1420/8.52.0.138//skype4life; timezone=Asia/Shanghai
x-ecs-etag: "BQJ655K30Esqwx0fw5omRbvzuwip35dxJZA+Qejf+QU="
Accept-Language: zh-cn
Accept-Encoding: br, gzip, deflate
Accept: application/json
Content-Length: 0
authentication: skypetoken=eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwMSIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzA0Mzc4MzMsImV4cCI6MTU3MDUyNDIzMywic2t5cGVpZCI6ImxpdmU6LmNpZC43ODEyNjcyYzczODFkNDg3Iiwic2NwIjo5NTYsImNzaSI6IjE1NzA0Mzc4MzMiLCJjaWQiOiI3ODEyNjcyYzczODFkNDg3IiwiYWF0IjoxNTcwMzg4OTM4fQ.NRrfKb4Xs1eTcjogS06d02ka_i-nxoEuVYI6wFcSRCfnquM-4MviK2dDB8lI2O_fhcF4SRa_azsNAD8aRXuF0YnX6KUOl8cvsfgoeRkbGiYhRnLtIqqF_8JkbodasOxF3X4vbHgWUs9XFsVGJWT2t7y4qMCZk9eZrRf-4OOkSVOd5JQdIx_qJb7j9oCOHE1FafCieCXYIjG3Ev-NetNYhSmzW94vm6quR6wXGXLxT3XN4Z9jYeCW20V0dCT4h0mej_YewKNLAoHowwvu628swpR-ygFEySO9u2-nIUy2NICSCCQEWgVg9MRySGrsoq-NsxqGDKLmknbJIdBKvgYhFg
User-Agent: Skype4Life/8.52.0.138 CFNetwork/978.0.7 Darwin/18.7.0
Connection: keep-alive

**Comment by Terrance** [comment]
Interesting, looks like they support PUT and DELETE now.

**Comment by a97077088** [comment]
Yes, I've written it. Can you patch it up?



Def delete (self):

""

Delete the message and remove it from the conversation.



Equivalent to call: meth: `edit'with an empty `content' string.



Returns:

SkypeMsg: copy of the deleted message object

""

Self.skype.conn ("DELETE", "{0}/users/ME/conversations/{1}/messages/{2}"). format (self.skype.conn.msgsHost, self.chat.id, self.id),

Auth = SkypeConnection. Auth. RegToken)

# print ("{0}/ users/ME/conversations/{1}/ messages/{2}"). format (self. skype. Conn. msgsHost, self. chat. id, self. id)

# return self. edit ("")
