### ISSUE TITLE
Flags API dropped

### ISSUE THREAD

**Issue by a97077088** [Terrance/SkPy#113]
HTTPSConnectionPool(host='flagsapi.skype.com', port=443): Max retries exceeded with url: /flags/v1 (Caused by NewConnectionError('<urllib3.connection.
VerifiedHTTPSConnection object at 0x0000000003732B00>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接
的主机没有反应，连接尝试失败。'))

**Comment by Terrance** [comment]
Looks like that endpoint has been silently removed...

**Comment by a97077088** [comment]
Does this project support donation

**Comment by timmy8526** [comment]
Encountered the same problem, will this be released in next version?
How could I update my skpy to include this fix?

**Comment by PetPython** [comment]
My appreciations to the @Terrance as well.

**Comment by Terrance** [comment]
Just pushed v0.9.1 to PyPI with the fix.
