### ISSUE TITLE
Another change in api.scheduler.skype.com, Connection timed out error.

### ISSUE THREAD

**Issue by alex-mlk** [Terrance/SkPy#115]
Hi, 
It seems another Skype endpoint was removed recently api.scheduler.skype.com

### Account type

Microsoft account

### Conversation details

I'm getting this error during creating a group chat conversation, however, the chat is created.

### Steps to reproduce

Create a group chat conversation, set a topic and try to get join URL by calling method .joinUrl

### Result or traceback

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.scheduler.skype.com', port=443): Max retries exceeded with url: /threads (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb66e876c>: Failed to establish a new connection: [Errno 110] Connection timed out',))

**Comment by Terrance** [comment]
Creating a conversation doesn't trigger that API call -- the only place that host is called is when inspecting `SkypeChat.joinUrl`.  You only pasted the exception so I don't know what you did to trigger that, but if you avoid that attribute then you should be clear for now.

Replacement API call seems to be `POST https://api.join.skype.com/v1/meetings`.
