### ISSUE TITLE
can not display mentioned properly

### ISSUE THREAD

**Issue by Samurais** [Terrance/SkPy#116]
If sending like this

```
ch.sendMsg('''Comment <at id="8:live:.cid.xx">bar</at> foo''')
```

The received message is notified as "You are mentioned", but the message is corrupt in the chat window. 

![image](https://user-images.githubusercontent.com/3538629/67007961-1f1e4800-f11b-11e9-801d-e9a5c099da06.png)

**Comment by Terrance** [comment]
Looking at the messages received from Skype, the syntax hasn't changed.  Going to need more info here.

**Comment by piotr-sarna** [comment]
Hello @Terrance, at first thank you for this piece of software, it's very helpful!

I encountered similar issues with mentions as @Samurais. I tried to implement mentioning all users in the chat and here are is the screenshot how it's look like:
![botToChatDisplay](https://user-images.githubusercontent.com/14096285/73666628-5ea97980-46a3-11ea-8385-ebb98d73b62f.png)
Here is the raw message that is sent by skpy library:
![botToChat](https://user-images.githubusercontent.com/14096285/73666629-5ea97980-46a3-11ea-863d-fcc6d578a5c1.png)

On the other hand, when I send the same mention using Skype client it's look like this:
![userToBotDisplay](https://user-images.githubusercontent.com/14096285/73666627-5e10e300-46a3-11ea-83cc-436f8ebe5640.png)
Here is the raw message that skpy received:
![userToBot](https://user-images.githubusercontent.com/14096285/73666626-5e10e300-46a3-11ea-9ab9-64c36faf862d.png)

I'm using:
- skpy 0.9.1 with Python 3.5.2
- Skype 8.56.0.103 for Windows

Thank you in advance for your help. Best regards!

**Comment by Terrance** [comment]
> `<at id="*">all</at>`

Is this a new feature, or a redaction?  What happens if you send a proper user ID?

---

In any case, you need to compare with the API call Skype for Web makes when you send a mention in the browser.  Presumably there is an extra field missing somewhere.

**Comment by piotr-sarna** [comment]
Regarding `<at id="*">all</at>`, I've put there just an hard-coded string using following code  
`event.msg.chat.sendMsg(content='<at id="*">all</at>', rich=True)`. And it doesn't matter what text I put inside the tag, result is the same.

OK, I'll check it against Skype for Web. Thanks!

**Comment by piotr-sarna** [comment]
Good news is: it's not a problem with skpy :)
Bad news is: Skype mentions for `all` people are properly formatted ONLY for account that sent it. All other users will see that additional `@` symbol at the beginning.

This problem(?) reproduces for Skype for Web, iOS, Android and Windows. 

Note: mentions for single user works fine for me, if you use `rich` modifier.

**Comment by Terrance** [comment]
This appears to be a quirk of Skype for Web, and possibly intentional?  The singular `@` appears to be being used like an icon, perhaps to indicate you're mentioned in the message.  The message content is accurate and doesn't contain the `@`, sending from either SkPy or Skype for Web.

@Samurais The original issue reported was also due to a lack of use of `rich=True`, which is required for any markup such as mentions (see [`SkypeChat.sendMsg()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChat.sendMsg)).
