### ISSUE TITLE
fileContent writing

### ISSUE THREAD

**Issue by razvanwaz** [Terrance/SkPy#119]
Hi! I'm trying to write the fileContent that is received in a image-message, but it seems the file is corrupt after I write to it. I've compared the contents of the initial image and the contents of the "downloaded" and they looks similar. Any ideas?

This is the code I use: 
```
        		if isinstance(event.msg, SkypeImageMsg):
        			save_image(event.msg)
```
```
	def save_image(image):
		f = open("img.png", "w")
		f.write(image.fileContent)
		f.close()
```

**Comment by Terrance** [comment]
Images are binary format, but you're writing a text file which will likely break the file format -- see the `mode` parameter of Python's [`open()`](https://docs.python.org/3/library/functions.html#open), you want `open(..., "wb")`.

**Comment by razvanwaz** [comment]
It worked. Thank you very much!
