### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by razvanwaz** [Terrance/SkPy#120]
Does skpy support the use of proxies? I've been looking through the code, but I didn't find anything.

**Comment by Terrance** [comment]
SkPy uses the Requests library for HTTP requests, which supports the use of [`HTTP_PROXY` and `HTTPS_PROXY` environment variables](http://docs.python-requests.org/en/latest/user/advanced/#proxies) out of the box.  Does that cover your use case?

**Comment by razvanwaz** [comment]
Yes, thank you very much for the support.
