### ISSUE TITLE
Exception for utf user name

### ISSUE THREAD

**Issue by mftun** [Terrance/SkPy#123]
I have non-ascii user name in skype. When send message i got exception:
```
...
File "untitled0.py", line 16, in <module>
    ch.sendMsg (u'test')

  File "/home/.../.local/lib/python2.7/site-packages/skpy/chat.py", line 179, in sendMsg
    imdisplayname="{0}".format(self.skype.user.name), **kwargs)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)
```

I found this line in user.py, in method SkypeUser.Name:
`return " ".join(filter(None, (self.first, self.last)))`

and change it to:

`return " ".join(filter(None, (self.first.encode('utf-8'), self.last.encode('utf-8'))))`

and all work. Possible bad solution. Im new in python.

**Comment by Terrance** [comment]
Are you using Python 2?  Works fine as-is on Python 3 with a mixed Greek/Japanese/symbol character name.

**Comment by mftun** [comment]
Yes it's python 2

**Comment by Terrance** [comment]
As Python 2 is well past end-of-life now, and the unicode-default strings of Python 3 will handle this fine, I'm not sure the effort to find all affected fields and add the decoding boilerplate is worth it now.  You should switch to Python 3 if you're in need of full Unicode handling.
