### ISSUE TITLE
Reauthenticate token in a SkypeEventLoop

### ISSUE THREAD

**Issue by gacalixto** [Terrance/SkPy#126]
I'm having some issues trying to figure out how to reauthenticate my token in a SkypeEventLoop.
What's the best way to do it?

I log in using a Microsoft account

**Comment by Terrance** [comment]
If you provided the account password to the constructor then you don't need to, it will reauthenticate for you when the token expires.  The Microsoft account flow requires you to go via the login page each time, so you can't renew with only a token file.

**Comment by gacalixto** [comment]
Hmm if first, i establish a SkypeConnection using:
`sk_int = Skype(conta_json['user'],conta_json['senha'],token_file)`

and the i construct my event loop using this:
`sk = MySkype(tokenFile=(token_file), autoAck=True)`

Will it reauthenticate?
Or do i need to pass my user and my password to the eventLoop constructor also?

**Comment by Terrance** [comment]
`SkypeEventLoop` is a subclass of `Skype`, and accepts the same email/password arguments -- you should only be using one of them.

**Comment by gacalixto** [comment]
hmm ok, so i don't need to use both?
Is it obligatory to use a token file when starting a loop?
I think i misunderstood the real use of the token file...

**Comment by Terrance** [comment]
If you're providing the password every time (e.g. prompting the user with `getpass`) then you probably don't need a token file.  It exists to persist your current session without needing to reauth.

Microsoft account logins are unable to refresh their session (they're effectively bounced back to the login page, requiring state for `login.live.com`), meaning it will usually last at most 24 hours.  Previously, everyone had a Skype username and password, and it was possible to refresh an existing token without re-entering the password, so the token file would continue to work.

**Comment by gacalixto** [comment]
In my case, when I initiate the loop, the email and password are provided,
and after that, i don't ask the user to provide the password again.
The reason behind this is that my project uses the account as a Messaging
bot for helpdesk support.

**Comment by gacalixto** [comment]
Another question, when my account receives more than one message in a short time interval, it shows them out of order on my console log.
Is that normal behavior?

**Comment by Terrance** [comment]
They're returned in the order the server produces them, so if Skype sends events out of order then that's how you'll receive them.  If that's a problem, and the events are arriving in a single long-poll call, you could override [`Skype.getEvents()`](https://skpy.t.allofti.me/api.html#skpy.main.Skype.getEvents) to sort them first:

```python
def getEvents():
    return sorted(super().getEvents(), key=lambda e: e.time)
```

If they're turning up in separate long-polls, you'd have to buffer them locally to sort before yielding.

**Comment by gacalixto** [comment]
in my case, i use onEvent(), for handling incoming messages instantly and for that reason it bugs me that skype receives them out of order.
