### ISSUE TITLE
SkypePresenceEvent Not fired

### ISSUE THREAD

**Issue by yoloSwagSEO** [Terrance/SkPy#130]
I'm trying to retrieve the status change from my contacts.
I seem to have succeeded a few months ago, but I'm not saving anything...

This is my code
```
from skpy import Skype
sk = Skype(connect=False)
from skpy import SkypeEventLoop,SkypePresenceEvent
class MySkype(SkypeEventLoop):
    def onEvent(self, event):
            print(event)
            

sk = MySkype(tokenFile=".tokens-app", autoAck=True)
sk.loop()
```

I get a lot of events when I change my status.
Or when I talk to a contact.
But no events when a contact changes their status :/

**Comment by rickdsanchez** [comment]
I can confirm this. No SkypePresence events are received from any contacts.

This started about 2 months ago and wasn't caused by any changes in my code.

**Comment by Terrance** [comment]
Looking at Skype for Web, it seems to make two subscription requests now: one as we do currently, but a second that subscribes to presence events for each contact individually.

**Comment by Terrance** [comment]
You'll need to call [`Skype.subscribePresence()`](https://skpy.t.allofti.me/api.html#skpy.main.Skype.subscribePresence) before event polling starts to enable them again.

**Comment by rickdsanchez** [comment]
Awesome! It worked. Installed the latest Github version and SkypePresence events are back.
