### ISSUE TITLE
question: how to get the names of non-contact member in a group conversation?

### ISSUE THREAD

**Issue by pidongqianqian** [Terrance/SkPy#132]
I didn't find any information about this, if anyone knows and tells me how to get it, thank you！

**Comment by Terrance** [comment]
[`SkypeGroupChat.users`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.users) holds a [`SkypeUser`](https://skpy.t.allofti.me/api.html#skpy.user.SkypeUser) list, regardless of whether they're contacts or not.

**Comment by pidongqianqian** [comment]
> [`SkypeGroupChat.users`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.users) holds a [`SkypeUser`](https://skpy.t.allofti.me/api.html#skpy.user.SkypeUser) list, regardless of whether they're contacts or not.

thanks, i got it
