### ISSUE TITLE
sendMsg not working after working for 1 day

### ISSUE THREAD

**Issue by starraw** [Terrance/SkPy#133]
hi, i'm facing some issue with response POST 400 which it did not appear initially. I was able to send msg to individual and groupchat. everything was working wonderful. but after running a day of the script, it suddenly stop working and showing this error. have try debug_http and result return was this.

`
C:\Program Files\Python\Python38-32>python ga.py
<= [08/07 09:05:59] GET https://api.skype.com/users/self/profile
{}
=> [08/07 09:06:00] 200
{'Cache-Control': 'must-revalidate, no-cache, stratus-cache-per-request=true',
 'Connection': 'keep-alive',
 'Content-Length': '323',
 'Content-Type': 'application/json; ver=1.0; charset=utf-8',
 'Date': 'Wed, 08 Jul 2020 01:06:00 GMT',
 'Server': 'nginx/1.12.2',
 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;',
 'Vary': 'Origin',
 'X-Azure-Instance-ID': 'ProfileFrontend_IN_6',
 'X-Azure-Location': 'WestEurope',
 'X-Content-Type-Options': 'nosniff',
 'X-Frame-Options': 'SAMEORIGIN',
 'X-Processing-Time': '0.079',
 'X-Skype-Processing-Time': '5.22900',
 'X-Skype-Request-Id': '7a9f392c',
 'X-Stratus-Endpoint': '/users/:username/profile',
 'X-Stratus-Processing-Time': '0.0773',
 'X-XSS-Protection': '1; mode=block'}
{'about': None,
 'avatarUrl': None,
 'birthday': None,
 'city': None,
 'country': None,
 'emails': [],
 'firstname': 'jlee12',
 'gender': '0',
 'homepage': None,
 'jobtitle': None,
 'language': None,
 'lastname': None,
 'mood': None,
 'phoneHome': None,
 'phoneMobile': None,
 'phoneOffice': None,
 'province': None,
 'richMood': None,
 'username': 'live:.cid.b85e099e598aff85'}
<= [08/07 09:06:00] GET https://contacts.skype.com/contacts/v2/users/live:.cid.b
85e099e598aff85
{'params': {'delta': '', 'reason': 'default'}}
=> [08/07 09:06:00] 200
{'Cache-Control': 'no-cache, no-store, must-revalidate, private, max-age=0',
 'Content-Encoding': 'gzip',
 'Content-Type': 'application/json; charset=utf-8',
 'Date': 'Wed, 08 Jul 2020 01:05:59 GMT',
 'ETag': '"g|0000|0000000000000000003|2020-07-08T01:06:00.3366452Z"',
 'Server': 'Microsoft-HTTPAPI/2.0',
 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains',
 'Transfer-Encoding': 'chunked',
 'Vary': 'Accept-Encoding',
 'X-Correlation-Id': '8baa512c-540c-4ab5-a902-ee17ea7d7653',
 'X-Role-Instance': 'e3e978678a95436ea898a2c6719134b4/4',
 'X-Session': 'eyI3Ung5QWJQeXlaQXYvZz09IjoiMTg3MTotMSMyMDM0MzA0MSJ9'}
{'blocklist': [],
 'contacts': [{'authorized': True,
               'blocked': False,
               'creation_time': '2020-07-06T22:40:14.0809348Z',
               'display_name': 'jlee',
               'display_name_source': 'profile',
               'explicit': True,
               'mri': '8:live:jasperlee88',
               'person_id': '8:live:jasperlee88',
               'profile': {'name': {'first': 'jlee'},
                           'skype_handle': 'live:jasperlee88'},
               'relationship_history': {'sources': [{'time': '2020-07-06T22:40:1
4.0809348Z',
                                                     'type': 'init_conversation'
}]}},
              {'authorized': True,
               'blocked': False,
               'creation_time': '2020-07-06T22:38:52.2605081Z',
               'display_name': 'Echo / Sound Test Service .',
               'display_name_source': 'profile',
               'explicit': True,
               'mri': '8:echo123',
               'person_id': '8:echo123',
               'profile': {'about': 'Hi, this is Skype automatic sound test '
                                    'service. Add me to your contact list and '
                                    'give me a call to test your sound setup. '
                                    'See https://www.skype.com/go/help for '
                                    'more assistance. Thank you.',
                           'avatar_url': 'https://avatar.skype.com/v1/avatars/ec
ho123?auth_key=242200701',
                           'language': 'en',
                           'locations': [{'country': 'gb', 'type': 'home'}],
                           'name': {'first': 'Echo / Sound Test Service',
                                    'surname': '.'},
                           'skype_handle': 'echo123',
                           'website': 'https://www.skype.com/go/help'}}],
 'groups': [],
 'scope': 'full'}
<= [08/07 09:06:00] GET https://azwus2-client-s.gateway.messenger.live.com/v1/us
ers/ME/conversations/8:live:jasperlee88
{'params': {'view': 'msnp24Equivalent'}}
=> [08/07 09:06:02] 200
{'Cache-Control': 'no-store, must-revalidate, no-cache',
 'Content-Encoding': 'gzip',
 'Content-Length': '450',
 'Content-Type': 'application/json; charset=utf-8',
 'ContextId': 'tcid=1439090704552885493,server=BY3PEPF00008583',
 'Date': 'Wed, 08 Jul 2020 01:06:01 GMT',
 'Pragma': 'no-cache',
 'X-Content-Type-Options': 'nosniff'}
{'id': '8:live:jasperlee88',
 'lastMessage': {'conversationLink': 'https://azwus1-client-s.gateway.messenger.
live.com/v1/users/ME/conversations/8:live:jasperlee88',
                 'from': 'https://azwus1-client-s.gateway.messenger.live.com/v1/
users/ME/contacts/8:live:jasperlee88',
                 'type': 'Message'},
 'lastUpdatedMessageId': 1594121669769,
 'lastUpdatedMessageVersion': 1594121669769,
 'messages': 'https://azwus1-client-s.gateway.messenger.live.com/v1/users/ME/con
versations/8:live:jasperlee88/messages',
 'properties': {'clearedat': '1594129750535',
                'consumptionhorizon': '1594077014820;1594129744888;1594077014698
',
                'conversationstatus': 'Accepted',
                'isemptyconversation': 'False',
                'lastimreceivedtime': '2020-07-07T11:34:29.761Z',
                'onetoonethreadid': '447a8c2fb0973aadf528cfc684e13c44553ab9e866a
98dd98290491faeef5deb@oneToOne.skype',
                'processedClearedAt': '1594129750535'},
 'targetLink': 'https://azwus1-client-s.gateway.messenger.live.com/v1/users/ME/c
ontacts/8:live:jasperlee88',
 'type': 'Conversation',
 'version': 1594148275454}
<= [08/07 09:06:02] POST https://azwus2-client-s.gateway.messenger.live.com/v1/u
sers/ME/conversations/8:live:jasperlee88/messages
{'json': {'Has-Mentions': 'false',
          'clientmessageid': '1594170362079',
          'content': '.',
          'contenttype': 'text',
          'imdisplayname': 'jlee12',
          'messagetype': 'Text'}}
=> [08/07 09:06:02] 400
{'Content-Length': '111',
 'Content-Type': 'application/json; charset=utf-8',
 'ContextId': 'tcid=8535153037782196035,server=BY3PEPF00008583',
 'Date': 'Wed, 08 Jul 2020 01:06:02 GMT'}
{'errorCode': 201,
 'message': 'Either "startTime", "startComposeTime"query string parameter must '

            'be provided'}
Traceback (most recent call last):
  File "ga.py", line 14, in <module>
    ch.sendMsg(".")
  File "C:\Program Files\Python\Python38-32\lib\site-packages\skpy\chat.py", lin
e 178, in sendMsg
    return self.sendRaw(editId=edit, messagetype=msgType, content=content,
  File "C:\Program Files\Python\Python38-32\lib\site-packages\skpy\chat.py", lin
e 115, in sendRaw
    msgId, arriveTime = self.createRaw(msg)
  File "C:\Program Files\Python\Python38-32\lib\site-packages\skpy\chat.py", lin
e 51, in createRaw
    resp = self.skype.conn("POST", "{0}/users/ME/conversations/{1}/messages"
  File "C:\Program Files\Python\Python38-32\lib\site-packages\skpy\conn.py", lin
e 219, in __call__
    raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code,
 method, url), resp)
skpy.core.SkypeApiException: ('400 response from POST https://azwus2-client-s.ga
teway.messenger.live.com/v1/users/ME/conversations/8:live:jasperlee88/messages',
 <Response [400]>)

C:\Program Files\Python\Python38-32>`

i'm not sure what is the issue. can someone help me out. i try different skype account but does not work anymore as well.

**Comment by starraw** [comment]
oh.. i try created a new skype account and it is working again. can someone tell me why is it so? is it due to the auth limit? i already set token though. not sure why this happen.

**Comment by Terrance** [comment]
Another case of #124?

**Comment by starraw** [comment]
Hi Terrance, so sorry i guess its similar case but #124 is asiic character issue. i realize mine is token issue.. any idea how it can be resolve? i'm having the same issue once again and i just change to a new token name to get it working back. is there any way i can code it to refresh the token after certain hours. i'm using this skpy module for a my skype account to automate sending msg whenever something trigger. It is working really fine and wonderful but just happen to have this token issue which i need to keep changing after the API error appears. 

Hope you can guide me along like what i can include in my code to resolve this token issue, i'm not really an expert in the programming and still learning on python.

my code is something like this.

`from skpy import Skype, SkypeChat
Skype("testtest", "getpass()", ".tokens-testtest") # connect to Skype
sk = Skype(tokenFile=".tokens-testtest")`


while True:
    time.sleep(1)
    try:
        driver.find_element_by_xpath("//td[contains(text(), '--')]")

    except NoSuchElementException:
        driver.refresh()

    else:
       acctype = find_row.find_element_by_xpath("//*[@id='main']/div/div/div[2]/div/div[2]/table/tbody/tr/td[3]").text
       ch = sk.chats['19:d19********************@thread.skype']
       ch.sendMsg(acctype)
       continue`

really appreciate your kind help

**Comment by Terrance** [comment]
Are you saying it always works for a day after each startup?  If you're using password auth each time, it should refresh the token for you, though the error message is dubious and could be masking something else.

**Comment by starraw** [comment]
> Are you saying it always works for a day after each startup? If you're using password auth each time, it should refresh the token for you, though the error message is dubious and could be masking something else.

Hi Terrance, yes it last approximate a day and will get an error after that. I will need to manually delete the token from the python folder and restart my script to get it working again. somehow it did not refresh the token as mention by you.

Can you see from my previous post where did i go wrong in my script? I'm using the while loop to send the msg(acctype) whenever driver detect "--" text in 1 of the td column. 

Do i need to define the token(Skype(tokenFile=".tokens-testtest") again before sendMsg? 


Appreciate a million thanks if you can assist.

**Comment by Terrance** [comment]
I've left a test account connected for a few days, and sending messages after the token expires triggers the refresh and posts without any issues.  If you're sure it's correlated with the token expiry (check `sk.conn.tokenExpiry`), I'm to assume it's account-specific (or perhaps gateway-specific?) weirdness.  Are all operations failing at that point, or just sending messages?

**Comment by starraw** [comment]
> I've left a test account connected for a few days, and sending messages after the token expires triggers the refresh and posts without any issues. If you're sure it's correlated with the token expiry (check `sk.conn.tokenExpiry`), I'm to assume it's account-specific (or perhaps gateway-specific?) weirdness. Are all operations failing at that point, or just sending messages?

Hi Terrance,
Thanks for testing it out for me. Actually the problem seems to be solve unknowingly. My script has been running for days without failing. Somehow what i did is i logout from web skype instead of login in.  Was guessing might be due to idling? Not really sure why but it is working fine for me after i did that.
