### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id' when accessing SkypeMsg.deleted

### ISSUE THREAD

**Issue by suurjaak** [Terrance/SkPy#135]
An error occurred upon accessing SkypeMsg.deleted:

    Traceback` (most recent call last):
      File "<input>", line 1, in <module>
        if msg.deleted:
      File "C:\Program Files (x86)\Python\lib\site-packages\skpy\msg.py", line 260, in deleted
        return self.html == ""
      File "C:\Program Files (x86)\Python\lib\site-packages\skpy\msg.py", line 670, in html
        conTag = makeTag("part", identity=user.id)
    AttributeError: 'NoneType' object has no attribute 'id'

The offending message:

    SkypeCallMsg(id=u'1593784617947', type=u'Event/Call',
        time=datetime.datetime(2020, 7, 3, 13, 56, 57, 949000), 
        clientId=u'3666747505059875266', 
        userId=u'live:someliveuser', chatId=u'8:live:someliveuser', 
        content=u'<partlist type="ended" alt="" callId="1593784540478"><part identity="live:someliveuser"><name>Some Live User</name><duration>84.82</duration></part><part identity="8:someusername"><name>Some Name</name><duration>84.82</duration></part></partlist>',
        state=SkypeCallMsg.State.Ended, 
        userIds=[u'live:someliveuser', u'8:someusername'],
        userNames=[u'Some Live User', u'Some Name']
    )

Looks like the problem is that '8:someusername' is not the actual plain username but has the magic "8:" prefix, and so `self.skype.contacts[id]` in `util.py:userObjs` returns None.

**Comment by Terrance** [comment]
Two issues here, I think:

* We're not doing any processing of the user ID list, which makes it seem like a bug on Skype's end that Live users are non-prefixed but legacy users are (`live:` is a valid user type, unlike `8:` which is a chat type).  Wrapping with `noPrefix()` should handle that though, as it copes with IDs with or without a prefix.
* Checking if a message is deleted shouldn't depend on the HTML parsing.
