### ISSUE TITLE
hey i know nothing about anything help if you can

### ISSUE THREAD

**Issue by zilla213** [Terrance/SkPy#143]
I dont know anything about code. note 1 bit. I also dont know anything in github, so i dont know if this is the best place to say this, but i get a log in failure when trying to create new database couldnt retrieve t field from login response. I think there might be a fix that ive seen? but i cant understand the jargon so it literally means nothing to me. Im able to log onto the website and thats the only thing I could understand to do. thanks for the help

**Comment by zilla213** [comment]
i do have it linked with my microsoft account. I think ive read through the jargon and am now downlaoding sky py 0.10 which if im correct would help?

**Comment by Terrance** [comment]
v0.10 replaces the old method of logging in under the hood with one that still works, as long as your Skype account is linked to a Microsoft account with an email address.
