### ISSUE TITLE
cannot use skype username instead of email. FailedAuthentication exception occurs

### ISSUE THREAD

**Issue by ali-sajjad-rizavi** [Terrance/SkPy#144]
I tried these two methods to login:
```
sk = Skype('live:sasrizavi_1', 'mypassword')
# And also tried this...
sk = Skype('sasrizavi_1', 'mypassword')
```
This gives authentication failure. Only my email works.

**Comment by Terrance** [comment]
Probable side-effect of 0.10 changing the authentication method, and not something we have any control over.  If using your email address works then great, use that going forward -- it should work with both the new and the legacy flow (which will be restored soon, but will remain secondary to the new flow).

**Comment by ali-sajjad-rizavi** [comment]
But the docs say it is a `username` and `password` in the `Skype()` constructor :-( .

**Comment by Terrance** [comment]
The fields are named `user` and `pwd`, and that won't be changing without a break to backwards compatibility.  As noted, the different authentication mechanisms accept both usernames and email addresses, so username is more general than email.

The docs describe it as being either:

> If `user` and `pwd` are given, they will be passed to `SkypeConnection.setUserPwd()`. This can be either a Skype username/password pair, or a Microsoft account email address and its associated password.

...though perhaps this needs clarifying to say it depends on which auth flow is being used.

**Comment by sresasi** [comment]
I was facing the same issue. Go through the following link. It worked for me.
https://github.com/Terrance/SkPy/issues/141#issuecomment-679153879
