### ISSUE TITLE
'Account action required (https://lw.skype.com/login/oauth/proxy), login with a web browser first', <Response [200]>

### ISSUE THREAD

**Issue by yf33** [Terrance/SkPy#145]
branch "live-login-fix"  login failed 

'Account action required (https://lw.skype.com/login/oauth/proxy), login with a web browser first', <Response [200]>

**Comment by Terrance** [comment]
Does the 0.10 release work?  Have you actually followed the instruction to login with a web browser first?  Have you tried using [`liveLogin()`](https://skpy.t.allofti.me/internal.html#skpy.conn.SkypeConnection.liveLogin) which is what this branch is supposed to fix the behaviour of?

**Comment by dfelici87** [comment]
Hi,
I have the same problem and I try to follow your instructions... but doesn't work.

 - With a web browser the login success at domain "https://login.live.com/"
 - "liveLogin" function return the same error "'Account action required (https://lw.skype.com/login/oauth/proxy), login with a web browser first', <Response [200]>"

Can you help me?

**Comment by Terrance** [comment]
Microsoft's login pages are fickle and designed not to be automated -- if you can't get the interstitial page to show in a browser (on the same IP address) then not much can be done.  You might have some luck saving the HTML you get back (catch the exception and check `ex.args[1].text`) and opening it in a browser, though it'll likely just redirect away.

Note that this issue is stale -- by default in SkPy 0.10.2 you'll get SOAP authentication if you provide Microsoft account credentials, which works a lot more consistently as long as you have your Skype and Microsoft accounts linked.

**Comment by zodman** [comment]
this issue happend to my(when i loggin) and show this html:

```
<html><head><noscript>JavaScript required to sign in<meta http-equiv="Refresh" content="0; URL=https://login.live.com/jsDisabled.srf?mkt=EN-US&lc=1033&uaid=34e2b0c7d32942a98734645e2470c90f&client_flight=ReservedFlight33,ReservedFligh"/><
/noscript><title>Continue</title><script type="text/javascript">function OnBack(){}function OnNext(){}function DoSubmit(){var subt=false;if(!subt){subt=true;document.fmHF.submit();}}</script></head><body onload="javascript:DoSubmit();"><
form name="fmHF" id="fmHF" action="https://lw.skype.com/login/oauth/proxy?client_id=578134&site_name=lw.skype.com&redirect_uri=https%3A%2F%2Fweb.skype.com%2F&wa=wsignin1.0" method="post" target="_top"><input type="hidden" name="pprid" id
="pprid" value="31c175fac3c6fdb7"><input type="hidden" name="NAP" id="NAP" value="V%3D1.9%26E%3D1912%26C%3DEEZxzJFNRjIfl4-_TxpDj7l5uTStBDnMuEiXIjNYqddKw_e2To7xFA%26W%3D1"><input type="hidden" name="ANON" id="ANON" value="A%3DF611CABD8C30
8084B2430624FFFFFFFF%26E%3D196c%26W%3D1"><input type="hidden" name="t" id="t" value="EgD7AQMAAAAMgAAADQABba3AIgILY4Pc75Rb8FDVpTkT3c51yCljWfiu9tPk2G/Si92D05CYTbNxd7u5ugp99gmtTv9WkkCEjvgBXZV8QXDeKKVWaLCDJ58xtUNuNhHT4A1UHCYg0/0OCQXzGkMRFYdY
u+o99JU5wSyHxIOWrK+oSLKgfXkV//PgMpP/bIHbuqoGXCxMKcTaKjD5l3fZf2rmFQfoc1x3i/XHtAuNwxQ+ssofFEfO6gnisTymiwZsUu4MHeJe2T67UPi3N4/YdjuFOs8uh3YhpmSGWMDKfLVeeyuhwcBLzb3ELGCONXtmvC7TWKBI4SGgW/K8F/9b6OWekC/D2B4dJQbE2+440eoAewDqAAFAAwA1fdeAUcyKYFHMi
mCqeQQAChAggBAAADoAAAAAAABSVU0AAAAAAAAAAAIAAJHPVUAQFkEABkFuZHJlcwAGVmFyZ2FzAAAAAAAAAAAAAAAAAAAAAAAAw8b9tzHBdfoAAFHMimBRcwFhAAAAAAAAAAAAAAAAEAAxODcuMTkwLjE5MS4xMTEABQMAAAAAAAAAAAAAAAABAAAAAAAAAAAAADZAb1oAADaTb+AWGZ1CAAAAAAAAAAAAAAAAAAAAAA
AACgB6b2RtYW4xMDEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMA"></form></body></html>
```
The fmHF it is showed so, there some action required. I login and not action is required ... and every login fmHF is showed and not required to do any action... 
whats the problem ?

**Comment by Terrance** [comment]
What's the traceback for that login?  You have a `t` value so the auth should have been successful.

**Comment by zodman** [comment]
> What's the traceback for that login? You have a `t` value so the auth should have been successful.

i update the TB.

**Comment by Terrance** [comment]
If you update `SkypeLiveAuthProvider.sendCreds` to read the `t` field out, does it work?

```diff
 def sendCreds(self, user, pwd, params):
     # Now pass the login credentials over.
     loginResp = self.conn("POST", "{0}/ppsecure/post.srf".format(SkypeConnection.API_MSACC),
                             params={"wa": "wsignin1.0", "wp": "MBI_SSL",
                                     "wreply": "https://lw.skype.com/login/oauth/proxy?client_id=578134&site_name="
                                             "lw.skype.com&redirect_uri=https%3A%2F%2Fweb.skype.com%2F"},
                             cookies={"MSPRequ": params["MSPRequ"], "MSPOK": params["MSPOK"],
                                     "CkTst": "G{0}".format(int(time.time() * 1000))},
                             data={"login": user, "passwd": pwd,
                                 "PPFT": params["PPFT"], "loginoptions": "3"})
     opid = re.search(r"""opid=([A-Z0-9]+)""", loginResp.text, re.I)
     if opid:
         return opid.group(1)
+    tField = BeautifulSoup(loginResp.text, "html.parser").find(id="t")  # line 634 of conn.py
+    if tField is not None:
+        return tField.get("value")
     loginPage = BeautifulSoup(loginResp.text, "html.parser")
     for form in loginPage.findAll("form"):
         if form["name"] == "fmHF":
             url = form["action"].split("?", 1)[0]
             raise SkypeAuthException("Account action required ({0}), login with a web browser first"
                                         .format(url), loginResp)
     else:
         raise SkypeApiException("Couldn't retrieve opid field from login response", loginResp)
```

**Comment by zodman** [comment]
It  works now! should I create a PR ?

**Comment by Terrance** [comment]
I've just pushed a [`live-auth-refactor`](https://github.com/Terrance/SkPy/compare/live-auth-refactor) branch which rewrites the flow to accept the token field at any point, as well as catch 2FA-enabled accounts and display a more helpful error.

@zodman If you could check this continues to work for your account, that'd be handy.
