### ISSUE TITLE
Sync contacts / mass check for registration in skype

### ISSUE THREAD

**Issue by bahkadomos** [Terrance/SkPy#147]
Is there any way to check phone numbers for registration in skype via SkPy? I found a way to check contacts one by one via search. But I want to send a request with a list of contacts and receive checked list in response.

I installed skype on the android emulator, loaded VCF file with phones and sync them with address book. But skype doesn't sync with contacts on the device. So I can't track requests that are needed for sync.

**Comment by Terrance** [comment]
You can [search for contacts by name](https://skpy.t.allofti.me/api.html#skpy.user.SkypeContacts.search) -- that's all that was present in Skype for Web at the time, I'm not sure if that'll match phone numbers too.  Bulk lookup is unlikely to be present on the web as it's easily abused, and hammering the lookup API is liable to get you rate-limited.

If Skype for Web offers an interface for better lookups then it can probably be implemented here.
