### ISSUE TITLE
Support request: How can I log users who joined and left Group calls?

### ISSUE THREAD

**Issue by emarusso** [Terrance/SkPy#149]
I'm trying to log the users who actively participate to the groups calls that they share with my bot.
I don't know if this is even supported.

### Account type

I have a Live (Microsoft) account and I link successfully to web.skype.com

### Conversation details

I'm trying to log group conversations, I'd like to be able to write reports about users who actually joined a call in a group chat. 

### Steps to reproduce

- Create a group chat
- Add the bot
- add two more users

run this code: 
```
TokenFile= WorkingFolder + '\\.tokens-app'
sk = Skype(connect=False)
sk.conn.setTokenFile(TokenFile)
try:
    sk.conn.readToken()
except SkypeAuthException:
    # Prompt the user for their credentials.
    print('token not valid')
    username = input('Username: ')
    password = getpass()
    sk.conn.setUserPwd(username, password)
    sk.conn.getSkypeToken()

class MySkype(SkypeEventLoop):
    def onEvent(self, event):
        print(repr(event))

mysk = MySkype(tokenFile=WorkingFolder + '\\.tokens-app', autoAck=True)

mysk.loop()
```

- Start the call with one user
- Join with the other two
- Leave the conversation with one
- Join again

### Result or traceback

I expected to receive some event when someone joins or leaves, but I receive nothing. 
I asked myself how does the Web.skype.com know the number of the participants **in the call** 
and how it shows the popup when people joins and leaves.

**Comment by Terrance** [comment]
I assume calling uses a separate data stream as part of the call itself, and calling itself is out of scope.  SkPy attempts to listen for all the same events that Skype for Web does (which are declared up front), and from what I've seen it only sends an initial "first person started the call" and final "last person ended the call" events.

**Comment by emarusso** [comment]
Thanks for the confirmation, and for the quick answer. Do you know any
library or technology who might do this?
Thanks

Il mer 21 ott 2020, 00:21 Terrance <notifications@github.com> ha scritto:

**Comment by Terrance** [comment]
Not that I know of -- most Skype libraries wrap either Skype for Web (which is unofficial and undocumented, and doesn't appear to do this) or the Microsoft Bot API for Skype (which doesn't provide that kind of access).
