### ISSUE TITLE
How to mention all users in a group chat

### ISSUE THREAD

**Issue by Kyllingene** [Terrance/SkPy#153]
I do not know how to mention everyone in a group chat. No errors occurring, just a question.

Microsoft Account

Group Chat

Example of how it may work:
```
ch = sk.chats["chat_id"]
ch.mention("all") OR ch.mention_all()
```

Desired outcome: Mentions all users.

Note: I do realize I could simply get all users in a group, then mention them individually, but that would be relatively undesirable compared to mentioning using something like "@all". Thanks for the good work, keep it up!

**Comment by Terrance** [comment]
You'll need to add the markup manually:

```xml
<at id="*">all</at>
```

**Comment by Kyllingene** [comment]
Thank you!

**Comment by hastimal** [comment]
I still didn't get it. Can I see an example of this, please?

**Comment by Kyllingene** [comment]
> I still didn't get it. Can I see an example of this, please? @Terrance @Kyllingene

An example would be:

```
from skpy import Skype
sk = Skype(username,password)

chat = sk.chats["chat_id_123"]

chat.sendMsg("<at id="*">all</at> This mentions everyone!", rich=True)
```
