### ISSUE TITLE
'wsse:FailedAuthentication - Authentication Failure', <Response [200]>

### ISSUE THREAD

**Issue by bahkadomos** [Terrance/SkPy#156]
When logging in i get the following error:
'wsse:FailedAuthentication - Authentication Failure', <Response [200]>

Here is my auth code:
```
import sys
import settings as Settings
from skpy import Skype
from requests.adapters import HTTPAdapter
from requests.packages.urllib3.util.retry import Retry
from random import choice
import os


DEFAULT_TIMEOUT = 5


class TimeoutHTTPAdapter(HTTPAdapter):
	def __init__(self, *args, **kwargs):
		self.timeout = DEFAULT_TIMEOUT
		if "timeout" in kwargs:
			self.timeout = kwargs["timeout"]
			del kwargs["timeout"]
		super().__init__(*args, **kwargs)

	def send(self, request, **kwargs):
		timeout = kwargs.get("timeout")
		if timeout is None:
			kwargs["timeout"] = self.timeout
		return super().send(request, **kwargs)


def sk_connect(email, password, ua, proxy=None):
	retries = Retry(
		total=2,
		backoff_factor=1,
		status_forcelist=[429, 500, 502, 503, 504],
		method_whitelist=["HEAD", "GET", "POST", "PUT", "DELETE", "OPTIONS", "TRACE"]
	)

	s = Skype(connect=False)
	session = s.conn.sess
	session.mount("http://", TimeoutHTTPAdapter(max_retries=retries, timeout=5))
	session.mount("https://", TimeoutHTTPAdapter(max_retries=retries, timeout=5))

	session.proxies = proxy
	session.headers.update({'User-Agent': ua})

	token = f'{Settings.get("path")}/data/tokens/{email}'
	if not os.path.exists(token):
		if sys.platform == 'win32':
			open(token, 'w').close()
		else:
			os.mknod(token)

	s.conn.setTokenFile(token)
	try:
		s.conn.readToken()
	except:
		s.conn.setUserPwd(email, password)
		s.conn.getSkypeToken()
		s.conn.writeToken()
	return s



try:
	sk_connect(email, password, ua, proxy)
except Exception as e:
	logging.error(e)
```
I am creating an empty token file. After the script finishes, the file remains empty. What request is this error sent when?

I tested the accounts manually in a browser. They are authorized successfully, but Skype displays a message about entering reserve email. Could this error be related to reserve email?

**Comment by bahkadomos** [comment]
It's strange, but after many attempts the authorization is successful. After that, it is always authorized, even if the token file is deleted. I have tested on several accounts.

**Comment by bahkadomos** [comment]
Got it. Can I somehow find out on which request this error occurs?

**Comment by Terrance** [comment]
The traceback should tell you its coming from [here](https://github.com/Terrance/SkPy/blob/v0.10.1/skpy/conn.py#L763).

You can also just inspect `e.args[1]`, a [`Response`](https://2.python-requests.org/en/latest/api/#requests.Response) object from Requests, with the previously-sent request under [`Response.request`](https://2.python-requests.org/en/latest/api/#requests.Response.request).

**Comment by bahkadomos** [comment]
I tried to get last url with this code:
```
try:
	sk = Auth.sk_connect(email, password, ua, proxy)
except Exception as e:
	r = e.args[1].url
	logging.error(e)
	logging.error(r)
```
And this is what url I am getting: `https://login.live.com/RST.srf`

The exception is the same as before:
`'wsse:FailedAuthentication - Authentication Failure', <Response [200]>`

Can this information somehow help to identify an authorization problem?

**Comment by Terrance** [comment]
As stated already, that's all the information we get.  You can try switching to the old Live login flow with [`liveLogin()`](https://skpy.t.allofti.me/internal.html#skpy.conn.SkypeConnection.liveLogin) if you're not 2FA-protected, which might work out of the box, or at least give you a more helpful error.

**Comment by yf33** [comment]
try login https://web.skype.com  by chrome , F12 debug , network, get headers token update .token file 

`
root@i-07gufpnk:~/sky-bot# cat .token 
skype_id
eyJhbGciOiJSUzI1NiIsImtpZCI6IjEwMiIsInR5cCI5IkpXVCJ9.eyJpYXQiOjE2MDc0MDQzNTMsImV4cCI6MTYwNzQ5MDc1Miwic2t5cGVpZCI6Indvcmtfb3JkZXJfYm90Iiwic2NwIjo5NTgsImNzaSI6IjE2MDc0MDQzNTIiLCJjaWQiOiJjODk3NjljNWY5ZTc3NTc5IiwiYWF0IjoxNjA3NDA0MzQzfQ.EIyo5J76daBTl_trKzHPyAIz2uLArdGOx_6sK9puCNpnPy5_h9H5E3ulAq2kaYwEuAqcuSLxu42s26WG7rtVDWrp7IKBFjNO9Zg7rYf8d-Cr8EA0i7HyR9krmcbWrhuMNY0Trd_1-upo1CuY0m4mtQsdLj0kP0bFk-VVSIdntZDXTPn9yDf8J9bb7FeIcsTZZWCFlnQuDD_OYJnUr6er027JTJysEJD8H7Gw4Sz7H8FZxEA1HmEIzCAc1UsOISJJhZ7Hzdb1KbXGk4LQh03gXI_XcsrjX6U10Mi4n_dwuJp09UPBZdlRWk44P92JuhUFomcEk3Ym24N3j4tXogcVgQ
1607490751
registrationToken=U3lnbmF0dXJlOjI6Mjg6QVFRQUFBQUJKMUJVN0xIVXlaOHlZKzRIZGFmMTtWZXJzaW9uOjY6MToxO0lzc3VlVGltZTo0OjE5OjUyNDkxMTYwMzAwMDI1NDgyNzk7RXAuSWRUeXBlOjc6MTo4O0VwLklkOjI6MTQ6d29ya19vcmRlcl9ib3Q7RXAuRXBpZDo1OjM2OmNmY2Y5OGExLWU4MjgtNDFkMC04YzRhLTI3NDVkN2M2MDM5OTtFcC5Mb2dpblRpbWU6NzoxOjA7RXAuQXV0aFRpbWU6NDoxOTo1MjQ5MTE2MDMwMDAyMjM1Nzg5O0VwLkF1dGhUeXBlOjc6MjoxNTtFcC5FeHBUaW1lOjQ7MTk6NTI0OTExNjg5Mzk0NzM4NzkwNDtVc3IuTmV0TWFzazoxMToxOjI7VXNyLlhmckNudDo2OjE6MDtVc3IuUmRyY3RGbGc6MjowOjtVc3IuRXhwSWQ6OToxOjA7VXNyLkV4cElkTGFzdExvZzo0OjE6MDtVc2VyLkF0aEN0eHQ6Mjo0MDA6Q2xOcmVYQmxWRzlyWlc0T2QyOXlhMTl2Y21SbGNsOWliM1FCQTFWcFl4UXhMekV2TURBd01TQXhNam93TURvd01DQkJUUXhPYjNSVGNHVmphV1pwWldSNWRlZjV4V21YeUFBQUFBQUFBRUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFPZDI5eWExOXZjbVJsY2w5aWIzUUFBQUFBQUFBQUFBQUhUbTlUWTI5eVpRQUFBQUFFQUFBQUFBQUFBQUFBQUFCNWRlZjV4V21YeUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQVE1M2IzSnJYMjl5WkdWeVgySnZkQUFBQUFBQVFBdlBYd2dBQUFBRFZXbGpDRWxrWlc1MGFYUjVEa2xrWlc1MGFYUjVWWEJrWVhSbENFTnZiblJoWTNSekRrTnZiblJoWTNSelZYQmtZWFJsQ0VOdmJXMWxjbU5sRFVOdmJXMTFibWxqWVhScGIyNFZRMjl0YlhWdWFXTmhkR2x2YmxKbFlXUlBibXg1QUFBPTs=
1607490752 
https://client-s.gateway.messenger.live.com/v1
`
try to connect skype ... it work 
`
from skpy import Skype 
print("...connect...")
sk = Skype(username, password, tokenFile='.token')
print("conted")
`
