### ISSUE TITLE
HELP, Very serious, Skype account BANNAED/LOCKED/BLACKLIST by skype offical.

### ISSUE THREAD

**Issue by leemengwei** [Terrance/SkPy#157]
Hi Terrance, I've followed your project for quite some time. It helps a lot, so many thanks first.
Yet recently I got into trouble with skype official locking my account (forever, not the kind that requires verification code). FYI, I used email to sign in, and usually send about 2000 report messages a day to my clients.
At first skype notified me about abnormal, yet I can still log in.
Recently I was banned from login and then banned again, time to time after I register a new account, or even after I managed to retrieve my account from skype service (I was happy at first),  YET I was just send like about just 100 of messages a day, still, locked, banned. This could be deadly for my work, I almost quit. (sad)
Have you ever have similar issue, what's your advice?  Perhaps it's about adding too much new contacts, or sending to much msgs （some are sent to strangers） 
Do appreciate your work, thanks. 

### Account type

I used email to register and login, thus perhaps a Microsft account?

**Comment by Terrance** [comment]
I've not had any of my accounts suspended, nor have I heard of others in this situation, but I've also not sent that volume of messages, nor do I send messages to non-contacts (which if done frequently is very likely to be treated as spam).

Account automation in general is likely frowned upon (building a custom client is a reasonable use case, bulk-sending unsolicited messages is not), and in any case it sounds like you should be using the [official bot framework](https://dev.botframework.com) for this.

If you've had multiple accounts suspended now then they're likely applying closer scutiny to your IP address or some other identifying piece of information.

**Comment by leemengwei** [comment]
Got your message，thanks. I'll consider ur advice and infos. I am a vessel broker，so not for spamming～
