### ISSUE TITLE
How to authenticate with phone as a username?

### ISSUE THREAD

**Issue by bahkadomos** [Terrance/SkPy#160]
I used to log in with email and everything was fine. Now I decided to try accounts verified by SMS. The username for such accounts is the phone number. In the browser, by phone, authorization is successful, but in the script I get an error:
wsse:FailedAuthentication - Authentication Failure.

My authentication:
```
s.conn.setTokenFile(token)
try:
	s.conn.readToken()
except SkypeAuthException:
	s.conn.setUserPwd(email, password)
	s.conn.getSkypeToken()
	s.conn.writeToken()
```

**Comment by Terrance** [comment]
You'll probably need an email address on the Microsoft account in order to use SOAP authentication.  As discussed before, use `liveLogin()` for the legacy flow that supports usernames and phone numbers, as long as 2FA isn't enabled.

**Comment by bahkadomos** [comment]
I thought the authorization method is determined automatically (I use 1.0.1 SkPy version).
![Screenshot_1](https://user-images.githubusercontent.com/67415729/101833031-70706e80-3b49-11eb-9393-805b01789476.png)

With this code
```
s = Skype(connect=False)
s.conn.setTokenFile(token)
try:
	s.conn.readToken()
except SkypeAuthException:
	s.conn.setUserPwd(email, password)
	s.conn.liveLogin(email, password)
	s.conn.getSkypeToken()
	s.conn.writeToken()
```

or this
```
s = Skype()
s.conn.liveLogin(email, password)
```

I get an error:
`Account action required (https://lw.skype.com/login/oauth/proxy), login with a web browser first`

What does it mean?

**Comment by Terrance** [comment]
> I thought the authorization method is determined automatically

That change is in git but [not in a release yet](https://github.com/Terrance/SkPy/compare/v0.10.1...master).

>     s.conn.setUserPwd(email, password)
>     s.conn.liveLogin(email, password)

`liveLogin()` replaces `setUserPwd()`, they both store credentials but just choose the authentication method differently.

> I get an error

You're hitting a consent screen from the Microsoft account login flow, so not much can be done unless you can reproduce it in a browser on the same IP address and click through it.
