### ISSUE TITLE
How to prevent chat participants from sending messages?

### ISSUE THREAD

**Issue by bahkadomos** [Terrance/SkPy#161]
Is there any way to prevent group chat participants from sending messages? So that they can only join the chat, but cannot write anything in it.

Also the question: in the documentation I saw the **topic** and **users** methods of the **[SkypeGroupChat](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat)** class. I try to send them like this:
`sk.chats.create(users=user_ids, topic='Some Subject')`
but no messages are sent.

This is how it works:
```
ch = sk.chats.create(user_ids)
ch.setTopic('Some Subject')
```

But I haven't found any separate classes to set other methods.

**Comment by Terrance** [comment]
> Is there any way to prevent group chat participants from sending messages?

SkPy isn't magic, it only wraps features provided by Skype for Web, and read-only chat membership is not one of them.

> `sk.chats.create(users=user_ids, topic='Some Subject')`

Read the docs -- [`SkypeChats.create()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChats.create) accepts neither of those parameters.

> But I haven't found any separate classes to set other methods.

Like what?  Group chats have [`setTopic()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.setTopic), [`setOpen()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.setOpen) and [`setHistory()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.setHistory); single chats aren't configurable.

**Comment by bahkadomos** [comment]
> Like what? Group chats have [`setTopic()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.setTopic), [`setOpen()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.setOpen) and [`setHistory()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeGroupChat.setHistory); single chats aren't configurable.
How to set picture, for example?

**Comment by Terrance** [comment]
That picture field has been a source of confusion in the past (e.g. #134), so uploading remains unimplemented at present.  Pull requests welcome if you can get an upload to work.
