### ISSUE TITLE
Error in msg.py

### ISSUE THREAD

**Issue by sergeygladysh** [Terrance/SkPy#163]
Error appears when deleting messages with images (RichText/UriObject) and generic files (RichText/Media_GenericFile).

### Account type
Any

### Conversation details
Any

### Steps to reproduce
1. Start event listener
2. Send image to skpy user
3. Delete sent message

### Result or traceback
Exception has occurred: TypeError
object of type 'NoneType' has no len()
  File "C:\..\skpy\msg.py", line 566, in rawToFields
    file = BeautifulSoup(raw.get("content"), "html.parser").find("uriobject")
  File "C:\..\skpy\msg.py", line 251, in fromRaw
    return msgCls(skype, raw, **msgCls.rawToFields(raw))

Stupid, but quick fix:
...
file = None
if raw.get("content") is not None
...

    @classmethod
    def rawToFields(cls, raw={}):
        fields = super(SkypeFileMsg, cls).rawToFields(raw)
        # BeautifulSoup converts tag names to lower case, and find() is case-sensitive.
        file = None
        if raw.get("content") is not None
            file = BeautifulSoup(raw.get("content"), "html.parser").find("uriobject")
        if file:
            fileFields = {"name": (file.find("originalname") or {}).get("v"),
                          "size": (file.find("filesize") or {}).get("v"),
                          "urlFull": file.get("uri"),
                          "urlThumb": file.get("url_thumbnail"),
                          "urlView": (file.find("a") or {}).get("href")}
            fields["file"] = SkypeFileMsg.File(**fileFields)
        return fields

**Comment by Terrance** [comment]
I can't reproduce this, the delete just comes through as an edited event as expected:

```
[SkypeNewMessageEvent]
Id: 1011
Type: NewMessage
Time: 2021-01-12 23:09:25
MsgId: 1610492965516
[SkypeChatUpdateEvent]
Id: 1012
Type: ConversationUpdate
Time: 2021-01-12 23:09:25
ChatId: 8:joe.4
Horizon: None
[SkypeEditMessageEvent]
Id: 1013
Type: NewMessage
Time: 2021-01-12 23:09:32
MsgId: 1610492972328
[SkypeChatUpdateEvent]
Id: 1014
Type: ConversationUpdate
Time: 2021-01-12 23:09:32
ChatId: 8:joe.4
Horizon: None
```

You've also cut off the useful parts of the traceback -- please post your code and the full traceback.

**Comment by sergeygladysh** [comment]
As I can see, you don't try to get msg, that's why you did not reproduce.

Code to reproduce:

from skpy import SkypeEventLoop, SkypeNewMessageEvent, SkypeMessageEvent,SkypeEditMessageEvent,SkypeMsg

class MySkype(SkypeEventLoop):
    def onEvent(self, event):
        if isinstance(event, (SkypeNewMessageEvent,SkypeMessageEvent,SkypeEditMessageEvent)):
            print(repr(event))
            print(event.msg)

sk = MySkype(user, pwd,'c:\\...\\token.txt')
sk.loop()


Traceback (most recent call last):
  File "c:/.../reproduce.py", line 11, in <module>
    sk.loop()
  File "c:\...\skpy\main.py", line 213, in loop
    self.cycle()
  File "c:\...\skpy\main.py", line 202, in cycle
    self.onEvent(event)
  File "c:/.../reproduce.py", line 8, in onEvent
    print(event.msg)
  File "c:\...\skpy\util.py", line 227, in wrapper
    cache[key] = fn(*args, **kwargs)
  File "c:\...\skpy\event.py", line 170, in msg
    return SkypeMsg.fromRaw(self.skype, self.raw.get("resource", {}))
  File "c:\...\skpy\msg.py", line 251, in fromRaw
    return msgCls(skype, raw, **msgCls.rawToFields(raw))
  File "c:\...\skpy\msg.py", line 566, in rawToFields
    file = BeautifulSoup(raw.get("content"), "html.parser").find("uriobject")
  File "C:\Users\1\AppData\Local\Programs\Python\Python38-32\lib\site-packages\bs4\__init__.py", line 310, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()

**Comment by Terrance** [comment]
You didn't say to, hence why I asked for a full sample. 🙂

Seems like most of the message types are likely to be affected by this, if `content` is absent from the deleted message.  Previously it was there but an empty string, as deleting was equivalent to editing to an empty message -- maybe that changed a while ago when they implemented proper message deletion.
