### ISSUE TITLE
loosing the SkypeTextMsg object when itterating through the list of msgs

### ISSUE THREAD

**Issue by HassanAbbas7357** [Terrance/SkPy#165]
i want to delete all the messages of all conversations that are older than 48 hours
but when i want to itterate over a list of messages and delete i cannot delete the messages please have a look at my code.

when iam itterating at filer_old_messages 
for msg in msgs:
        msg

the value of msg i am getting is this:

[SkypeTextMsg]
Id: 1606130410220
Type: RichText
Time: 2020-11-23 11:20:05.596000
ClientId: 11201302558127693454
UserId: live:.cid.8ed3804eae146773
ChatId: 8:alyboghani
Content: 

what value of msg i think i need is this:
 

SkypeTextMsg(id='1606130410220', type='RichText', time=datetime.datetime(2020, 11, 23, 11, 20, 5, 596000), clientId='11201302558127693454', userId='live:.cid.8ed3804eae146773', chatId='8:alyboghani', content='')

i think iam loosing the object of class SkypeTextMsg and getting raw data i looked ,
i donot know how can i reconstruct the object from raw data to make it able to delete kindly help

### Account type  --- normal user

<!--
from skpy import Skype
from datetime import datetime , timedelta
import time

class Skype_:
    def __init__(self,username,password):
        self.username = username
        self.password = password
        self.sk = Skype(self.username, self.password)
        
    def get_conversation_id_list(self):
        contacts_list = []
        
        for contact in self.sk.contacts:
            contacts_list.append(self.sk.contacts[contact.id].chat.id)
        
        return contacts_list
    
    def get_conversation_msgs(self, contact_id):
        conversation = []
        while True:
            time.sleep(1)
            msgs = None
            msgs = self.sk.chats[contact_id].getMsgs()
            
            if msgs == []:
                for i in range(10):
                    msgs = self.sk.chats[contact_id].getMsgs()
                    if msgs == []:
                        pass
                    else:
                            for msg in msgs:
                                 conversation.append(msg)
                break
            
            else:
                for msg in msgs:
                                 conversation.append(msg)
        return conversation
    
    def filter_conversation_old_msgs(self):
       now_time = datetime.now() - timedelta(hours=48)
        conversation_ids = self.get_conversation_id_list()
        
        for Id in conversation_ids:
            try:
                print('\n\n---------- :')
                msgs = self.get_conversation_msgs(Id)
               for msg in msgs:
                     if msgs.time < now_time:
                                   msg.delete()

            except:
                print(f"\n\n\nError Occured ------------- {id}\n\n\n")
 

obj = Skype_('username,password')

obj.filter_conversation_old_msgs()

**Comment by Terrance** [comment]
As far as I can see, you've not lost anything, those are both representations of the same message object -- most SkPy objects provide a read-friendly output when `str()`'d, presumably you are `print()`ing it in the first case:

```python
>>> msg
SkypeTextMsg(id='1606130410220', ...)
```
```python
>>> print(msg)
[SkypeTextMsg]
Id: 1606130410220
...
```

**Comment by HassanAbbas7357** [comment]
Then can you please try my script and tell me what you think? Why i can't
delete all the older msgs for all conversations kindly help fix that bug

**Comment by HassanAbbas7357** [comment]
https://pastebin.com/GWNHZh7M

**Comment by HassanAbbas7357** [comment]
from skpy import Skype
from datetime import datetime , timedelta
import time

class Skype_:
    def __init__(self,username,password):
        self.username = username
        self.password = password
        self.sk = Skype(self.username, self.password)
        
    def get_conversation_id_list(self):
        contacts_list = []
        
        for contact in self.sk.contacts:
            contacts_list.append(self.sk.contacts[contact.id].chat.id)
        
        return contacts_list
    
    def get_conversation_msgs(self, contact_id):
        conversation = []
        while True:
            time.sleep(1)
            msgs = None
            msgs = self.sk.chats[contact_id].getMsgs()
            
            if msgs == []:
                for i in range(10):
                    msgs = self.sk.chats[contact_id].getMsgs()
                    if msgs == []:
                        pass
                    else:
                        for msg in msgs:
                            conversation.append(msg)
                break
            
            else:
                for msg in msgs:
                    conversation.append(msg)
        
        return conversation
    
    def filter_conversation_old_msgs(self):
        conversation_ids = self.get_conversation_id_list()
        now_time = datetime.now() - timedelta(hours=48)
        
        for id in conversation_ids:
            try:
                print('\n\n---------- :',id)
                msgs = self.get_conversation_msgs(id)

                for msg in msgs:
                    if msg.time <now_time:
                        print(msg)
                        # msg.delete()
                        # print(msg.content, ' ------  ', msg.time)

            except:
                print(f"\n\n\nError Occured ------------- {id}\n\n\n")
            break

obj = Skype_(username,password)

**Comment by HassanAbbas7357** [comment]
ah735752@gmail.com you can send me the debugged code  here

**Comment by Terrance** [comment]
Quoting the more relevant part not included here:

```
> # when you call j[0]
# you will get
'''SkypeTextMsg(id='1608795158242', ...)
        '''
# but when you itterate over this j list the data will be messed up and you cannot call functions like j[0].delete()
'''
    for i in j:
        i.delete()    this will raise error
        '''
```

You haven't specified what the error is.  When you do, include a full traceback rather than just printing the error.

At first glance, `get_conversation_msgs()` returns a plain Python `list`, so if you can access items by index without issue, but not by iteration, then there's a more fundamental problem that your code isn't illustrating.

However:

> you can send me the debugged code here

I am not here to debug your code.  This is the place to report bugs and request help with the library, not with general use of Python.  Consider asking for help somewhere like [discuss.python.org](https://discuss.python.org) or [pythondiscord.com](https://pythondiscord.com).

**Comment by HassanAbbas7357** [comment]
sorry for the inappropriate information let me come to the point
now i cannot delete the message i myself observed that the script can delete the ' sent messages ' but now the ' received messages '
[skype_task - Jupyter Notebook.pdf](https://github.com/Terrance/SkPy/files/5889684/skype_task.-.Jupyter.Notebook.pdf)

**Comment by HassanAbbas7357** [comment]
I read the deleteRaw function in which you are doing edit msg = empty , thats why i can't delete recieved messages because i don't have permisions to edit the other's messages

**Comment by Terrance** [comment]
> skype_task - Jupyter Notebook.pdf

You've just leaked your Skype account username and password.  You'd best change your password ASAP.

> the deleteRaw function in which you are doing edit msg = empty

That was the old way of deleting messages; you can see in your traceback that this is no longer the case and it sends a proper delete request:

```
~\anaconda3\lib\site-packages\skpy\chat.py in sendRaw(self, editId, **kwargs)
    132                 arriveTime = self.editRaw(editId, msg)
    133             else:
--> 134                 arriveTime = self.deleteRaw(editId)
    135         else:
    136             # Skype timestamps are integers and in milliseconds, whereas Python's are floats and in seconds.

~\anaconda3\lib\site-packages\skpy\chat.py in deleteRaw(self, msgId)
     92
     93    def deleteRaw(self, msgId):
-->  94         resp = self.skype.conn("DELETE", "{0}/users/ME/conversations/obj.filter_conversation_old_msgs()
     95                                          .format(self.skype.conn.msgsHost, self.id, msgId),
     96                                auth=SkypeConnection.Auth.RegToken)
```

...and that's coming back as unauthorised.  Does Skype even let you delete received messages?  The Skype for Web UI doesn't show an option for it; where sent messages have a _Remove_ option, received have _Report_ in its place.  If Skype itself doesn't support this then there's nothing we can do about it.

**Comment by HassanAbbas7357** [comment]
Sir can we report spam msgs ?

**Comment by Terrance** [comment]
SkPy doesn't implement reporting messages, no.  Bulk-reporting all messages in a conversation will probably be seen as abuse and/or will end up flagging the other user, so it's not a sensible solution for removing conversation history.

**Comment by HassanAbbas7357** [comment]
Ok, thanks.

**Comment by HassanAbbas7357** [comment]
sir another thing sir the script is now deleting all my sent messages that are older than 48 hours working fine but its not deleting my sent messages from groups do you know why its not deleting them? 
[New Text Document.txt](https://github.com/Terrance/SkPy/files/5890630/New.Text.Document.txt)

**Comment by Terrance** [comment]
> its not deleting my sent messages from groups do you know why its not deleting them?

Because you're iterating over contacts, not groups.  Moved to #167.
