### ISSUE TITLE
'Account action required (https://account.live.com/identity/confirm), login with a web browser first', <Response [200]>

### ISSUE THREAD

**Issue by researcher26** [Terrance/SkPy#166]
When i tried to login by 

`sk=Skype(login, pwd)`

i catch the Exception

'Account action required (https://account.live.com/identity/confirm), login with a web browser first', <Response [200]>

May be somebody solve the problem? Give me advice please

**Comment by Terrance** [comment]
The exception tells you what you need to do.  Failing that, duplicate of #145.
