### ISSUE TITLE
Sk.chats is not  getting all the chats like sk.contacts does

### ISSUE THREAD

**Issue by HassanAbbas7357** [Terrance/SkPy#167]
As i do with sk.contacts to get all the contacts
For contact in sk.contacts:
       Contact.id

I can't itterate over sk.chats to get all the conversations ( chats , groups )
For chat in sk.chats:
      chat    #is not returning anything i want to get all the chats and groups and itterate through all of them so i can delete the all sent messages from groups and chats

**Comment by Terrance** [comment]
Iterating [`SkypeChats`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChats) will only give you what's in the cache; you need to use [`recent()`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeChats.recent).
