### ISSUE TITLE
How to download Richtext / generic file from conversation thread in skpy python? 

### ISSUE THREAD

**Issue by jonardcaguioa** [Terrance/SkPy#169]
i got this details but i dont know how to retrieve the file. 

{'skype': Skype(userId='***************'), 'raw': {'type': 'Message', 'amsreferences': ['0-eaua-d5-822ea9c***************f54cbb43d'], 'id': '1612880096455', 'conversationLink': 'https://azeus1-client-s.gateway.messenger.live.com/v1/users/ME/conversations/8:live:.cid.cb***************dbf0a63', 'version': '1612880096455', 'clientmessageid': '18068***************830', 'originalarrivaltime': '2021-02-09T14:14:46.972Z', 'conversationid': '8:live:.cid.cb5de3595dbf0a63', 'content': '<URIObject uri="https://api.asm.skype.com/v1/objects/0-eaua-d5-822ea***************1359e50f54cbb43d" url_thumbnail="https://api.asm.skype.com/v1/objects/0-eaua-d5-***************/views/original" type="File.1" doc_id="0-eaua-d5-***************">To view this file, go to: <a href="https://login.skype.com/login/sso?go=webclient.xmm&amp;docid=0-eaua-d5-***************">https://login.skype.com/login/sso?go=webclient.xmm&amp;docid=0-eaua-d5-***************</a><OriginalName v="PDF TEST.pdf"></OriginalName><FileSize v="151960"></FileSize></URIObject>', 'messagetype': 'RichText/Media_GenericFile', 'composetime': '2021-02-09T14:14:46.972Z', 'from': 'https://azeus1-client-s.gateway.messenger.live.com/v1/users/ME/contacts/8:live:.cid.***************'}, 'id': '1612880096455', 'type': 'RichText/Media_GenericFile', 'time': datetime.datetime(2021, 2, 9, 14, 14, 46, 972000), 'clientId': '***************', 'userId': 'live:.cid.cb5de3595dbf0a63', 'chatId': '8:live:.cid.cb5de3595dbf0a63', 'content': '<URIObject uri="https://api.asm.skype.com/v1/objects/0-eaua-d5-***************" url_thumbnail="https://api.asm.skype.com/v1/objects/0-eaua-d5-***************/views/original" type="File.1" doc_id="0-eaua-d5-***************">To view this file, go to: <a href="https://login.skype.com/login/sso?go=webclient.xmm&amp;docid=0-eaua-d5-***************">https://login.skype.com/login/sso?go=webclient.xmm&amp;docid=0-eaua-d5-***************</a><OriginalName v="PDF TEST.pdf"></OriginalName><FileSize v="151960"></FileSize></URIObject>', 'file': File(name='PDF TEST.pdf', size='151960', urlFull='https://api.asm.skype.com/v1/objects/0-eaua-d5-822ea9c3053bf2811359e50f54cbb43d', urlThumb='https://api.asm.skype.com/v1/objects/0-eaua-d5-***************/views/original', urlView='https://login.skype.com/login/sso?go=webclient.xmm&docid=0-eaua-d5-***************')}

**Comment by Terrance** [comment]
See [`SkypeFileMsg`](https://skpy.t.allofti.me/reference/api.html#skpy.msg.SkypeFileMsg) in the docs.

**Comment by jonardcaguioa** [comment]
Okay thanks. I'll check that

**Comment by jonardcaguioa** [comment]
by the way, i am getting an error consistently on this one

id_lists = []
        skype_instance = SkypeContacts(self.sk)

        try:
            search_results = skype_instance.search(applicant_name)
            if len(search_results) > 3 or not search_results:
                return None

            for result in search_results:
                result.__dict__
                result = vars(result)
                details = result["raw"]["skypeId"].lstrip("8:")
                id_lists.append(details)

            return id_lists

        except Exception as e:
            print("Limit exceeded(Getting cooldown).")
            logging.error(
                '[{}]:: Error encountered. Failed to search: "{}"'.format(str(date.today()), str(applicant_name)))
            time.sleep(1)
            return None

**Comment by jonardcaguioa** [comment]
thats almost same to this one https://github.com/Terrance/SkPy/issues/80.

But i dont find the solution. because my program was tasked to run every 30 mins

**Comment by Terrance** [comment]
You haven't given any output so I don't know what error you're getting.  If it's `Auth rate limit exceeded` then maybe every 30 minutes is still too often.

**Comment by jonardcaguioa** [comment]
> by the way, i am getting an error consistently on this one
> 
> id_lists = []
> skype_instance = SkypeContacts(self.sk)
> 
> ```
>     try:
>         search_results = skype_instance.search(applicant_name)
>         if len(search_results) > 3 or not search_results:
>             return None
> 
>         for result in search_results:
>             result.__dict__
>             result = vars(result)
>             details = result["raw"]["skypeId"].lstrip("8:")
>             id_lists.append(details)
> 
>         return id_lists
> 
>     except Exception as e:
>         print("Limit exceeded(Getting cooldown).")
>         logging.error(
>             '[{}]:: Error encountered. Failed to search: "{}"'.format(str(date.today()), str(applicant_name)))
>         time.sleep(1)
>         return None
> ```

the input in this is just a string. maybe a name or id.

**Comment by jonardcaguioa** [comment]
then how can i get rid of Auth rate limit exceeded? I always see it in the error logs

**Comment by Terrance** [comment]
Run your searches less often.  The search API is likely rate-limited to discourage its automation or scraping, and you risk your Skype account being blocked if you keep hitting limits.

**Comment by jonardcaguioa** [comment]
> Run your searches less often. The search API is likely rate-limited to discourage its automation or scraping, and you risk your Skype account being blocked if you keep hitting limits.

OKAYY. THANK YOU. NOTED ON THIS
