### ISSUE TITLE
SkPy: how to make a new line. \n doesn't work

### ISSUE THREAD

**Issue by Drill-N-Bass** [Terrance/SkPy#173]
Hello,

I'm using SkPy library for sending messages via skype. When I place a string with `\n` it doesn't print a new line in a message. How to solve it? 

Account type:  Live (Microsoft) account.

Steps to reproduce:

When I load something like this:

`cat\ndog\nhome`

It print's on Skype:

`cat\ndog\nhome`

Instead:
`cat`
`dog`
`home`

**Comment by Terrance** [comment]
You'll probably need to send a rich text message using HTML line breaks (`<br/>`):

```python
chat.sendMsg("cat<br/>dog<br/>home", rich=True)
```

**Comment by Drill-N-Bass** [comment]
Hi,
thank you for the fast reply. That was it!

part of my updated code:
```
def text_skype():
    """
    I cut the code here - it's irrelevant
    """
   
    # https://github.com/Terrance/SkPy/issues/173
    import re
    re.sub(r"\\n", "<br/>", output_text_all) # skype needs html line breaks
    return output_text_all
    

def skype_to_user():
    from skpy import Skype
    sk = Skype(entry_skype_login.get(), entry_skype_pass.get()) # connect to Skypesk.user 
    # Single chat
    ch = sk.contacts["live:.user_login.88888888"].chat # 1-to-1 conversationch.sendMsg(content) # plain-text message
    # https://github.com/Terrance/SkPy/issues/173
    msg = ch.sendMsg(
            text_skype(),
            rich=True) # skype needs html line breaks: "rich=True"
```

best regards
Paul Pedryc
