### ISSUE TITLE
Unable to use sk.contacts with skype login nickname hidden inside an object

### ISSUE THREAD

**Issue by Drill-N-Bass** [Terrance/SkPy#174]
My problem is that I'm unable to use `sk.contacts` with a skype login nickname hidden inside an object which contains some output from `for loop`. I've tested, that this output is the same as the login which - when typed directly: works.
The code below is part of my GUI's code.
I want to use `Tkinter` `checkbuttons`  for ticking particular users that will receive the message. After ticking them in my GUI, I hit `button` "submit message". This button uses the definition posted below.

for ex. this code works:

```
def submit_offers_to_selected_clients():
    
    from skpy import Skype
    sk = Skype(entry_skype_login.get(), entry_skype_pass.get()) # connect to Skypesk.user 
    login_from_clients_dict = {}
    
    
    check_buttons_dict = {
            "user 1":twovar,
            "user 2":threevar,
            "user 3":fourvar,
            "user 4":fivevar,
            "user 5":sixvar,
            "user 6":sevenvar
            }
    check_buttons_list = [twovar, threevar, fourvar, fivevar, sixvar, sevenvar]
    
    for name in check_buttons_list:
        if name.get() == True:
            for dict_name in check_buttons_dict:
                if name == check_buttons_dict[dict_name]:
                    
                    login_from_clients_dict[dict_name] = df_clients.loc[dict_name, "Skype Adress"]
                    print(login_from_clients_dict["user 1"])

    ch = sk.contacts[live:.cid.addcb0eebdebb4491e].chat        ##### HERE IS THE PROBLEM ( but in this case, all work)

    msg = ch.sendMsg(
            "text",
            rich=True) # skype needs html line breaks: "rich=True"
    msg
```

But when I will use anything else than the string: `live:.cid.addcb0eebdebb4491e` - inside `sk.contacts`, then this errors is displayed: **AttributeError: 'NoneType' object has no attribute 'chat'**

Example of this error:

```
def submit_offers_to_selected_clients():
    
    from skpy import Skype
    sk = Skype(entry_skype_login.get(), entry_skype_pass.get()) # connect to Skypesk.user 
    login_from_clients_dict = {}
    
    
    check_buttons_dict = {
            "user 1":twovar,
            "user 2":threevar,
            "user 3":fourvar,
            "user 4":fivevar,
            "user 5":sixvar,
            "user 6":sevenvar
            }
    check_buttons_list = [twovar, threevar, fourvar, fivevar, sixvar, sevenvar]
    
    for name in check_buttons_list:
        if name.get() == True:
            for dict_name in check_buttons_dict:
                if name == check_buttons_dict[dict_name]:
                    
                    login_from_clients_dict[dict_name] = df_clients.loc[dict_name, "Skype Adress"]
                    print(login_from_clients_dict["user 1"])

    ch = sk.contacts[login_from_clients_dict["user 1"]].chat        ##### HERE IS THE PROBLEM

    msg = ch.sendMsg(
            "text",
            rich=True) # skype needs html line breaks: "rich=True"
    msg
```
please note that this part: `login_from_clients_dict["user 1"]` is in output: live:.cid.addcb0eebdebb4491e  - and it's a string. So it's exactly the same string.  

I have no idea why It doesn't work. :(

Account type: Live (Microsoft) account

**Comment by Terrance** [comment]
If you're getting a contact back when using the user ID as a literal then you've confirmed it's a problem with your code rather than SkPy itself.

Key lookups on `SkypeContacts` will return `None` if the ID doesn't exist (which will cause that `AttributeError` if you don't look at what you get back), so you're likely not passing in the value you think you are -- try `print(repr(value))` to see exactly what you're passing in.

**Comment by Drill-N-Bass** [comment]
>  try print(repr(value)) to see exactly what you're passing in.
hello, yes that was it. The **true** login was '"live:.cid.addcb0eebdebb4491e"'. Additional quotes characters made this error. Thank you for your help!
