### ISSUE TITLE
skpy.core.SkypeAuthException: ('wsse:FailedAuthentication - Authentication Failure', <Response [200]>

### ISSUE THREAD

**Issue by djaygit** [Terrance/SkPy#179]
tried this code locally 
```
from flask import Flask
from skpy import Skype

app = Flask(__name__)
@app.route("/")
def hello_world():
    sk = Skype('XXX','XXXX,connect=True)
    contact = sk.contacts
    ch = sk.contacts["dXXXX"].chat
    ch.sendMsg("sending from bot")
    return "<p>Message sent!</p>"
```
it worked fine and sent the message,
tried the same code on cpanel server and i'm getting Auth failure error.

python version 3.8.6
Skpy version 0.10.4

**Comment by Terrance** [comment]
That error comes [straight from Microsoft](https://skpy.t.allofti.me/background/authentication.html#error-messages).  If you're sure you haven't made a typo between the two machines, try using [Live authentication](https://skpy.t.allofti.me/guides/login.html) if available for your account, or proxy a browser via the server's connection to see if the IP is restricted.
