### ISSUE TITLE
Request addition attrs in SkypeEndpointEvent (Event.py)

### ISSUE THREAD

**Issue by kingprapop** [Terrance/SkPy#180]
I try to add two attrs ( version , typ)

class SkypeEndpointEvent(SkypeEvent):

attrs = SkypeEvent.attrs + ("userId", "name", "capabilities", "version","typ")

    @classmethod
    def rawToFields(cls, raw={}):
        fields = super(SkypeEndpointEvent, cls).rawToFields(raw)
        res = raw.get("resource", {})
        fields.update({"userId": SkypeUtils.userToId(res.get("selfLink")),
                       "name": res.get("privateInfo", {}).get("epname"),
                       "capabilities": list(filter(None, res.get("publicInfo", {})
                                                            .get("capabilities", "").split(" | "))),
                       "version": res.get("publicInfo", {})
                                            .get("skypeNameVersion",{}),
                       "typ": res.get("publicInfo", {})
                                 .get("typ",{})})
        return fields

i used this "https://skpy.t.allofti.me/background/protocol/events.html" for refference

i already test it by myself

**Comment by Terrance** [comment]
Done in #183.
