### ISSUE TITLE
Can't send buttons in chat

### ISSUE THREAD

**Issue by Ussr-eng** [Terrance/SkPy#190]
how can i send a message with buttons in skype chat by this lib?help please.

```
ch = self.chats[id]

button_val = {"type": "postBack", "title": "button_tit", "value": "value_but"}
create_button = SkypeCardMsg.Button(**button_val)

card_val = {"title": "title_butt", "body": "body_butt", "buttons": [create_button]}
create_card = SkypeCardMsg(**card_val)

ch.sendRaw(content=create_card.html, messagetype="UriObject")
```

this code return:

`TypeError: <URIObject type="SWIFT.1" url_thumbnail="https://urlp.asm.skype.com/v1/url/content?url=https://neu1-urlp.secure.skypeassets.com/static/card-128x128.png">Card - access it on <a href="https://go.skype.com/cards.unsupported">https://go.skype.com/cards.unsupported</a>. <Swift b64="eyJ0aW1lc3RhbXAiOiIyMDIyLTAzLTE2VDIwOjUyOjU5LjQ4ODIzMloiLCJ0eXBlIjoibWVzc2FnZS9jYXJkIiwiYXR0YWNobWVudHMiOlt7ImNvbnRlbnQiOnsiYnV0dG9ucyI6W3sidHlwZSI6InBvc3RCYWNrIiwidmFsdWUiOiJ2YWx1ZV9idXQiLCJ0aXRsZSI6ImJ1dHRvbl90aXQifV0sInRleHQiOiJib2R5X2J1dHQiLCJ0aXRsZSI6InRpdGxlX2J1dHQifSwiY29udGVudFR5cGUiOiJhcHBsaWNhdGlvbi92bmQubWljcm9zb2Z0LmNhcmQuaGVybyJ9XX0="></Swift><Description></Description></URIObject> is not JSON serializable`

**Comment by Terrance** [comment]
`UriObject` is probably not the right type -- see https://github.com/Terrance/SkPy/issues/51#issuecomment-289908200 for an example, but see also the remaining comments on that issue (that user-sent cards may not render in clients).
