### ISSUE TITLE
8: before values

### ISSUE THREAD

**Issue by mihalt** [Terrance/SkPy#192]
Hi! Can't understand why, but I have 8: before contact `id` or `conversationid`. For example when call `skype_user.chats.recent()`

**Comment by Terrance** [comment]
Because you are looking at a chat and not a contact -- you probably want [`SkypeSingleChat.user`](https://skpy.t.allofti.me/reference/api.html#skpy.chat.SkypeSingleChat.user); see also [Terminology](https://skpy.t.allofti.me/background/terminology.html).
