### ISSUE TITLE
Docs adding

### ISSUE THREAD

**Issue by mihalt** [Terrance/SkPy#196]
Hi! Write here, please, that it is about incoming requests, not outgoing https://skpy.t.allofti.me/reference/api.html#skpy.user.SkypeContacts.requests

And can you explain me how to understand, was contact accepted my outgoing request? Are any better ways, than check presence of greeting message in conversation?

**Comment by Terrance** [comment]
> it is about incoming requests, not outgoing

There is no list of outgoing requests -- they are effectively fire-and-forget, and you can't accept/reject your own invite.

> was contact accepted my outgoing request

Skype doesn't expose that directly -- if you can see the acceptance in the chat's message history then that's probably your best indicator.
