### ISSUE TITLE
False as string?

### ISSUE THREAD

**Issue by mihalt** [Terrance/SkPy#199]
Hi! Say me, please, is it bug of feature? 'False' as string
![изображение](https://user-images.githubusercontent.com/30621622/170979570-2f4efd70-945f-492d-8b3c-0caa047ce59d.png)

**Comment by Terrance** [comment]
Neither -- `raw` contains the API response we got from the Skype API before processing.  The contents of `raw` fields are not guaranteed in any way and are subject to change if Skype make any changes to their APIs.
