### ISSUE TITLE
Easy way to parse quote

### ISSUE THREAD

**Issue by mihalt** [Terrance/SkPy#203]
Hi! Say me, please, are any easy ways in your lib to parse quotes from `SkypeTextMsg` to get tags data?

**Comment by Terrance** [comment]
There is not -- SkPy will generate limited markup for some message types, but not parse it.

Skype messages are generally in HTML format, so you can use a parser like [BeautifulSoup](https://beautiful-soup-4.readthedocs.io) (which you should already have installed as a dependency of SkPy) to work with them.
