### ISSUE TITLE
i cant triger an event loop

### ISSUE THREAD

**Issue by hannescam** [Terrance/SkPy#208]
i have tried the example on pypi:
`from skpy import SkypeEventLoop, SkypeNewMessageEvent
class SkypePing(SkypeEventLoop):
    def __init__(self):
        super(SkypePing, self).__init__("my-sercrete-email@outlook.com", "onepassword")
    def onEvent(self, event):
        if isinstance(event, SkypeNewMessageEvent) \
          and not event.msg.userId == self.userId \
          and "ping" in event.msg.content:
            event.msg.chat.sendMsg("Pong!")`
and nothing
if i messaged my account with the api running with "ping" nothing
but when i just send a message i works in both ways
please help,
i am making a game with this amazing api

**Comment by Terrance** [comment]
> when i just send a message i works in both ways

Are you saying if you send a message from a client then you can see it from SkPy, but specifically testing for a ping message doesn't catch it?  If so then that sounds like the condition isn't right -- you may find it useful to store received events somewhere, and poke them from the Python console to see why you're not catching it:

Modifying the [events example](https://skpy.t.allofti.me/guides/events.html):

```python
import code
from getpass import getpass
from skpy import SkypeEventLoop, SkypeNewMessageEvent


class MySkype(SkypeEventLoop):

    events = []

    def onEvent(self, event):
        print(repr(event))
        # Store the event for later:
        self.events.append(event)
        if isinstance(event, SkypeNewMessageEvent):
            # Start an interactive console to inspect message:
            code.interact(local=dict(globals(), **locals()))


if __name__ == "__main__":
    sk = MySkype("fred.2", getpass(), autoAck=True)
    sk.loop()
```
