### ISSUE TITLE
Can use "mail" to find his "SKYPE ID"? Example: his mail is "joe.bloggs@live.co.uk" to find "live:.cid.17c7653000"

### ISSUE THREAD

**Issue by nobody1225** [Terrance/SkPy#219]
Excuse me, everyone
Can use "mail" to find his "SKYPE ID"?
Example: his mail is "joe.bloggs@live.co.uk" to find "live:.cid.17c7653000"
thanks a lot.
^V^

**Comment by Terrance** [comment]
See [`SkypeContacts.search`](https://skpy.t.allofti.me/reference/api.html#skpy.user.SkypeContacts.search).
