### ISSUE TITLE
Error 403 when search for contacts

### ISSUE THREAD

**Issue by dracox76** [Terrance/SkPy#226]
When using Skype.search("whatever"), the library responds with a 403 error from the following URL

403 response from GET https://skypegraph.skype.com/search/v1.1/namesearch/swx/', <Response [403]>)

MS changed the endpoints or the permisions? when i try to browse that URL, it shows that the site can´t be reached.

**Comment by lol1990lol1990** [comment]
I have the same error when trying to search for contacts using mobile number

**Comment by neodymium001** [comment]
Hi @Terrance -  is it possible to push this change to PyPi?

**Comment by Terrance** [comment]
Released in [v0.10.6](https://github.com/Terrance/SkPy/releases/tag/v0.10.6) ([PyPI](https://pypi.org/project/SkPy/0.10.6/)).
