### ISSUE TITLE
to convert mobile numbers and email addresses to skype IDs?

### ISSUE THREAD

**Issue by goitin** [Terrance/SkPy#229]
I know that using the urlToIds method I can convert the group link to a group ID.
For example, convert join.skype.com/XXXXXX to 19:XXXXXX@thread.skype

So. is it possible to convert mobile numbers and email addresses to skype IDs?
For example converting +12223334444 or xxx@outlook.com to live:.cid.XXXXXXXX

The last question is:
 I have a group ID, can I join the group directly?

**Comment by Terrance** [comment]
> is it possible to convert mobile numbers and email addresses to skype IDs?

[`SkypeContacts.search`](https://skpy.t.allofti.me/reference/api.html#skpy.user.SkypeContacts.search) should match Skype for Web's search box, which likely supports searching by contact details, but note that #226 may hinder it currently.

> I have a group ID, can I join the group directly?

#221
