### ISSUE TITLE
Send message to some groups

### ISSUE THREAD

**Issue by Mkarting** [Terrance/SkPy#243]
Hi, i am new to this topic and this language, i'm trying to send the exctly same message at the exctly same time to 3 different groups in skype, im out of ideas how to do it, even chatgpt coldn't  help me out. By now, i have this code below.
`from skpy import Skype, 
import requests, time, schedule

# Substitua 'seu_email' e 'sua_senha' pelas suas credenciais do Skype
sk = Skype("...", "m...")

# Lista de IDs de contatos para os quais você deseja enviar a mensagem
contacts_ids = ['live:.cid.6000b2330b1a104c', 'live:.cid.a84ba69c28c5bfbd']

# Loop para enviar a mensagem para cada contato
for contact_id in contatos_ids:
    # Encontre o contato pelo ID
    contact = sk.contacts[contacts_ids] 

def send_message():
    # Coloque aqui o código para enviar a mensagem
    message = "Sua mensagem aqui"  # Substitua pela mensagem que você deseja enviar
    contact.chat.sendMsg(message)

    

# Agende o envio da mensagem às 15 horas todos os dias
schedule.every().day.at("15:00").do(send_message)

# O loop a seguir verifica regularmente se há tarefas agendadas para serem executadas
while True:
    schedule.run_pending()
    time.sleep(1)  # Você pode ajustar o intervalo de verificação, se desejar`

**Comment by Terrance** [comment]
You haven't said what your problem is, and the one bit of SkPy code (`sk.contacts[contact_id].chat.sendMsg(message)`) should work, so without any more context, either there's a problem elsewhere in your code or you're getting rate-limited from spamming your contacts every second if `run_pending()` actually triggers the sending every second.

**Comment by Mkarting** [comment]
Im getting de error 404
![image](https://github.com/Terrance/SkPy/assets/143124652/da0ecc2f-b989-4f2a-8f04-a050e49c703e)

**Comment by Mkarting** [comment]
This is acturaly a group, i'm trying to send a message to three different groups
![image](https://github.com/Terrance/SkPy/assets/143124652/bc9586b1-1602-4edd-af3f-6c768927a168)

**Comment by Terrance** [comment]
The code you posted originally does not create or interact with any groups, it's sending messages to individual users.  Please post the code you're actually running code in full, and show the corresponding output and errors.

Peeking at that traceback, that group ID doesn't look long enough.  Are you passing a user ID instead of a group chat ID?  You should also be using [key lookups on `sk.chats`](https://skpy.t.allofti.me/reference/api.html#skpy.chat.SkypeChats), no need to call `chat()`.

**Comment by Mkarting** [comment]
I don't even know if this makes sense at all, i'm new at dev and just trying this
![image](https://github.com/Terrance/SkPy/assets/143124652/44f52a25-53be-4086-ab6d-ed6c6760754c)

**Comment by Terrance** [comment]
No problems here reading a group like that:

```python
>>> group_id = "19:b07bbfdc71174e1b88e491c451824b99@thread.skype"
>>> group = sk.chats.chat(group_id)
>>> group
SkypeGroupChat(id='19:b07bbfdc71174e1b88e491c451824b99@thread.skype', alerts=True, topic='Test group', creatorId='8:fred.2', userIds=['8:fred.2'], adminIds=['8:fred.2'], open=False, history=False, active=False, moderated=False)
```

Or using key access as recommended earlier:

```python
>>> sk.chats[group_id]
SkypeGroupChat(id='19:b07bbfdc71174e1b88e491c451824b99@thread.skype', alerts=True, topic='Test group', creatorId='8:fred.2', userIds=['8:fred.2'], adminIds=['8:fred.2'], open=False, history=False, active=False, moderated=False)
```

Reiterating from above:

> Peeking at that traceback, that group ID doesn't look long enough. Are you passing a user ID instead of a group chat ID?

The prefix (`19:`) is correct so I'm unsure if you've actually obtained it from somewhere, or just manually typed an invalid ID.

`sk.contacts[group_id]` (line 21) also won't work, presumably you mean to use `group` there.

As far as I can tell, there's no issue with SkPy here, so please take some time to read the [Guides](https://skpy.t.allofti.me/guides/) section of the docs that explains how to do the basic tasks like retrieving users and chats.

**Comment by Mkarting** [comment]
Bro, your tip about de 

> The code you posted originally does not create or interact with any groups, it's sending messages to individual users. Please post the code you're actually running code in full, and show the corresponding output and errors.
> 
> Peeking at that traceback, that group ID doesn't look long enough. Are you passing a user ID instead of a group chat ID? You should also be using [key lookups on `sk.chats`](https://skpy.t.allofti.me/reference/api.html#skpy.chat.SkypeChats), no need to call `chat()`.

This tip solved my problems, thank you so much
