### ISSUE TITLE
Not able to send messages

### ISSUE THREAD

**Issue by peterp96** [Terrance/SkPy#244]
### Before we start...

- [X] I've searched existing issues, but my problem hasn't been reported yet.
- [X] I've read the documentation (including notes on error messages and rate limiting), but my problem is something else.
- [X] I've tested the behaviour on [Skype for Web](https://web.skype.com), and it works there but not with SkPy.

### Summary

I'm trying to send message but it's not working, It was working properly yesterday.

### Code sample

```python
from skpy import Skype

sk = Skype(username, password)

ch = sk.contacts['user-id'].chat # 1-to-1 conversation
ch.sendMsg('ok')
```

### Code output

```python
('400 response from POST https://azeus1-client-s.gateway.messenger.live.com/v1/users/ME/conversations/user-id/messages', <Response [400]>)
```

### Explain your code

I'm just sending a normal message.

### SkPy version

v0.10.6

### Python version

3.11.4

**Comment by Terrance** [comment]
You didn't include the full output, so I can't see what the response from Skype was.

From the issue form:

> Set the `SKPY_DEBUG_HTTP=1` environment variable so that requests to the Skype API are logged.

**Comment by eth** [comment]
Are you sure you're still able to message the user?
I get these 400 errors when trying to send to a chat I no longer have access to.
