### ISSUE TITLE
How to reply to a message?

### ISSUE THREAD

**Issue by un-hongly** [Terrance/SkPy#249]
Hi, I want to reply to a message. How can I achieve that?

**Comment by Terrance** [comment]
Skype for Web has historically not supported a reply mechanism; you would need to quote another message, which can be done in SkPy using [`SkypeMsg.quote()`](https://skpy.t.allofti.me/reference/api.html#skpy.msg.SkypeMsg.quote).

**Comment by un-hongly** [comment]
> Skype for Web has historically not supported a reply mechanism; you would need to quote another message, which can be done in SkPy using [`SkypeMsg.quote()`](https://skpy.t.allofti.me/reference/api.html#skpy.msg.SkypeMsg.quote).

Thank you!

**Comment by un-hongly** [comment]
can I quite with `messageid`? so when I click it it will jump to original message

```
<quote author="live:.cid.777f63dd1...." authorname="Full Name" timestamp="1706757811" conversation="...13e2fe9c34c4bd48b45e7b6cf01a722@thread.skype" messageid="1706757811330" cuid="17067578111.."><legacyquote>[1706757811] Full Name: </legacyquote>Provider is now closed.<legacyquote>
         
         &lt;&lt;&lt; </legacyquote></quote>Test
```

**Comment by Terrance** [comment]
I'm guessing that's a recent addition as Skype for Web has not previously offered any form of quotes linked to source messages.  You should be able to construct the message HTML yourself (this is all the various `SkypeMsg` helpers do) and send it in a regular message.  Pull requests are open if you wish to extend `SkypeMsg.quote()` with the extra metadata.
