### ISSUE TITLE
link from msg.urlContent is not stable?

### ISSUE THREAD

**Issue by un-hongly** [Terrance/SkPy#251]
When I receive a yesterday message I opened msg.urlContent it's working fine but today it's not. Seem it's not reliable. is this an issue from Skype?

**Comment by Terrance** [comment]
I'll need more than that to go on (working / not working how? what's the link?) -- please actually use the [issue templates](https://github.com/Terrance/SkPy/issues/new/choose) which ask for the information I need.

**Comment by un-hongly** [comment]
> I'll need more than that to go on (working / not working how? what's the link?) -- please actually use the [issue templates](https://github.com/Terrance/SkPy/issues/new/choose) which ask for the information I need.

Here it is.
https://github.com/Terrance/SkPy/issues/252
