### ISSUE TITLE
Image link from SkypeFileMsg.urlContent is not working

### ISSUE THREAD

**Issue by un-hongly** [Terrance/SkPy#252]
### Before we start...

- [X] I've searched existing issues, but my problem hasn't been reported yet.
- [X] I've read the documentation (including notes on error messages and rate limiting), but my problem is something else.
- [X] I've tested the behaviour on [Skype for Web](https://web.skype.com), and it works there but not with SkPy.

### Summary

When I open image link from SkypeFileMsg.urlContent is not working.

### Code sample

```python
class Bot(SkypeEventLoop):
    def __init__(self):
        self.username = os.getenv("SKYPE_USERNAME", "")
        self.password = os.getenv("SKYPE_PASSWORD", "")
        self.message_endpoint = os.getenv("MESSAGE_PUSH_ENDPOINT", "")
        super(Bot, self).__init__(
            self.username, self.password, tokenFile="tokenCred.txt", autoAck=True
        )

    def onEvent(self, event):
        try:
            if (
                isinstance(event, SkypeNewMessageEvent)
                and not event.msg.userId == self.userId
            ):
                print(event.msg.urlContent)
        except Exception as e:
            print(e)
```

### Code output

```python
https://sa1-api.asm.skype.com/v1/objects/0-sa-d3-4609d9b5340c3acebdb0b24f230fdfe2/views/imgpsh_fullsize
```

### Explain your code

I use SkypeEventLoop to listen for incoming message from a group. When someone sent an image I got an image link by using `event.msg.urlContent` but the link doesn't work.

### SkPy version

0.10.6

### Python version

3.11.7

**Comment by kingprapop** [comment]
I have same problem.
I asked  discussion zone -> https://github.com/Terrance/SkPy/discussions/253
@Terrance  please guild me about authentication.
Thank you

**Comment by Terrance** [comment]
For you the answer to the above question appears to be yes, but see further info on the discussion post.

In terms of SkPy's API here, as far as I can tell there is no issue with it presenting the URL and the corresponding file content.

**Comment by un-hongly** [comment]
> How are you accessing the link? It needs authentication to access, so won't work if e.g. you open it in your browser.
> 
> Are you looking for [`event.msg.fileContent`](https://skpy.t.allofti.me/reference/api.html#skpy.msg.SkypeFileMsg.fileContent)?

Thanks! I will use event.msg.fileContent instead.
