### ISSUE TITLE
How to delete other user's message in Moderated Group chat?

### ISSUE THREAD

**Issue by un-hongly** [Terrance/SkPy#258]
Hi, I tested in current version of Skype Web. In a Moderated Group Chat, admins are able to delete messages of other users. Can I achieve the same in using this library?

**Comment by Terrance** [comment]
Have you tried [`SkypeMsg.delete()`](https://skpy.t.allofti.me/reference/api.html#skpy.msg.SkypeMsg.delete)?

**Comment by un-hongly** [comment]
> Have you tried [`SkypeMsg.delete()`](https://skpy.t.allofti.me/reference/api.html#skpy.msg.SkypeMsg.delete)?
Now it works.
