### ISSUE TITLE
How to change status?

### ISSUE THREAD

**Issue by Miopha** [Terrance/SkPy#273]
### Before we start...

- [X] I've searched existing issues, but my request hasn't been submitted yet.
- [X] I've read the documentation, but my request is something new.
- [X] I've checked on [Skype for Web](https://web.skype.com), and the feature I'm requesting does exist there.

### Summary

Hello
First thank you so much for this project.
I need assistance in changing the account status within the application. However, I couldn't find any documentation on how to do this.
Is this feature available?

### Code sample

```python
"""
```

### SkPy version

8.128.0.207

### Python version

3.9

**Comment by Terrance** [comment]
I assume you're looking for [`Skype.setPresence`](https://skpy.t.allofti.me/reference/api.html#skpy.main.Skype.setPresence) with a [`Status`](https://skpy.t.allofti.me/reference/internal.html#skpy.util.SkypeUtils.Status)?
