### ISSUE TITLE
Exception while getting recent chats due to leaved non-public group chat

### ISSUE THREAD

**Issue by maxnikulin** [Terrance/SkPy#72]
After successful authentication I try to get chats (`sk` is a `skpy.Skype` instance)
```sk.chats.recent()```
I get an exception with the following trace
```
<path>/github/OllieTerrance/SkPy/skpy/chat.pyc in recent(self)
    413                 info = self.skype.conn("GET", "{0}/threads/{1}".format(self.skype.conn.msgsHost, json.get("id")),
    414                                        auth=SkypeConnection.Auth.RegToken,
--> 415                                        params={"view": "msnp24Equivalent"}).json()
    416                 json.update(info)
    417                 cls = SkypeGroupChat

<path>/github/OllieTerrance/SkPy/skpy/conn.pyc in __call__(self, method, url, codes, auth, headers, **kwargs)
    215             if resp.status_code == 429:
    216                 raise SkypeAuthException("Auth rate limit exceeded", resp)
--> 217             raise SkypeApiException("{0} response from {1} {2}".format(resp.status_code, method, url), resp)
    218         return resp
    219 

SkypeApiException: ('403 response from GET https://db4-client-s.gateway.messenger.live.com/v1/threads/19:I<SoMe-LeTtErS-aNd-DiGitS>@p2p.thread.skype', <Response [403]>)
```
It happens due to a private chat that I have leaved.

I would prefer to get a list with at least with accessible chats. Chats that I can not see may present but should be easily distinguishable.

### Account type
A skype account with no connection to a MS one.

### Conversation details
An old p2p group chat that I leaved some time ago.

### Steps to reproduce
I am unsure if it can be reproduced with a cloud group chats. I noticed it with a p2p one.
Join to a non-public chat and leave it. Perhaps some messages should be received in meanwhile. Try to get recent chats using `Skype.chats.recent()`

### Result or traceback
I hope that the trace given above will be enough.

### Workarond
The quick fix below is like a hammer, I think a much better solution exists.
```diff
diff --git a/skpy/chat.py b/skpy/chat.py
index bc3ad45..e7dab68 100644
--- a/skpy/chat.py
+++ b/skpy/chat.py
@@ -2,7 +2,7 @@ from datetime import datetime
 import re
 import time
 
-from .core import SkypeObj, SkypeObjs
+from .core import SkypeObj, SkypeObjs, SkypeApiException
 from .util import SkypeUtils
 from .conn import SkypeConnection
 from .msg import SkypeMsg
@@ -410,10 +410,14 @@ class SkypeChats(SkypeObjs):
         for json in resp.get("conversations", []):
             cls = SkypeSingleChat
             if "threadProperties" in json:
-                info = self.skype.conn("GET", "{0}/threads/{1}".format(self.skype.conn.msgsHost, json.get("id")),
-                                       auth=SkypeConnection.Auth.RegToken,
-                                       params={"view": "msnp24Equivalent"}).json()
-                json.update(info)
+                try:
+                    info = self.skype.conn("GET", "{0}/threads/{1}".format(self.skype.conn.msgsHost, json.get("id")),
+                                           auth=SkypeConnection.Auth.RegToken,
+                                           params={"view": "msnp24Equivalent"}).json()
+                    json.update(info)
+                except SkypeApiException as e:
+                    if e.args[1].status_code != 403:
+                        raise e
                 cls = SkypeGroupChat
             chats[json.get("id")] = self.merge(cls.fromRaw(self.skype, json))
         return chats
```

P.S. Thank you for the project, besides a couple of issues, the library works and is quite convenient.

**Comment by OllieTerrance** [comment]
That's an interesting catch.  Testing it here on a new group conversation after leaving, it appears to still let me make the thread call despite no longer being a member.  It could well be down the P2P-ness of the conversation, though I don't have any of those handy to play with.

We could handle this is by checking the list of members from the first request, and not making that second request if we're no longer a member, though that request holds most of the useful information for group chats.

---

As a small side-note:

> I noticed it with a p2p one.

The thread ID ends `@p2p.thread.skype`, which means it's still a cloud conversation, but one that was created from an old P2P chat (i.e. a separate conversation with the same participants).

**Comment by maxnikulin** [comment]
> We could handle this is by checking the list of members from the first request

Log messages got with `SKPY_DEBUG_HTTP=1` are jammed, but it seems that chats causing errors have no `members` field in properties. In responses to recent chat request (`users/ME/conversations`) I noticed `members` field only for a chat that is created by me.
Additional info. Server response to request of chat properties
```
 GET https://db4-client-s.gateway.messenger.live.com/v1/threads/19:<...>
<...>
 'Pragma': 'no-cache',
 'StatusText': 'You do not have sufficient privileges to execute this operation.'}
{u'errorCode': 209,
 u'message': u'You do not have sufficient privileges to execute this operation.'}
```
> The thread ID ends @p2p.thread.skype, which means it's still a cloud conversation

Maybe. I remember that some people complained that an old chat was inaccessible from the web-client. That time old linux client was working so I had no interest in python API and chat id formats. For a leaved chat without "p2p" in id, server sends member list in response to `v1/threads/` request. 403 code is specific to "p2p" threads.

**Comment by Terrance** [comment]
Whilst testing another issue, I just came across this but with a 404 (maybe some server-side garbage collection of old conversations that still appear in the recent list).  May as well add some handling for either status code -- I've included an ``active`` attribute on group conversations, which can be checked to see if the group still exists before trusting the rest of its data.
