### ISSUE TITLE
How does one catch contact request events

### ISSUE THREAD

**Issue by bundabrg** [Terrance/SkPy#79]
Sorry to pollute the issues but how does one catch a contact request event? Or is the only way to poll SkypeContacts periodically to enumerate all pending requests?

**Comment by OllieTerrance** [comment]
Not sure how Skype for Web handles it -- you'll probably receive a [`SkypeNewMessageEvent`](https://skpy.t.allofti.me/api.html#skpy.event.SkypeNewMessageEvent) at the time, so you could check your contact requests only if `event.user` isn't in your contacts and `event.chat` is a [`SkypeSingleChat`](https://skpy.t.allofti.me/api.html#skpy.chat.SkypeSingleChat) (as opposed to a group where non-contacts can contact you).  Currently there's no built-in way to detect new invites.

**Comment by bundabrg** [comment]
I'll do some digging. One issue is that after a contact request is sent you can never re-send it which makes debugging tricky. If I can work out what the raw API sends back I'll provide back a PR with a new event class that handles this.

**Comment by johannesstricker** [comment]
@bundabrg Any update on this? Facing the same problem.

**Comment by bundabrg** [comment]
Unfortunately I wasn't able to and ended moving my project from Skype. Good luck.

I'll close this.
