### ISSUE TITLE
Retrieving list of existing contacts

### ISSUE THREAD

**Issue by ExMachlna** [Terrance/SkPy#93]
Title. Is there a way to get a list of all contacts you alrady have chat with? I tried chats.recent(), but it retrieves even contacts for deleted chats.

**Comment by OllieTerrance** [comment]
You'll get back all conversations ever had, "deleted" (labelled more appropriately as "hidden" in most clients) or not.  Probably better to loop through `Skype.contacts` and check for a corresponding conversation in `SkypeChats`.

**Comment by OllieTerrance** [comment]
I thought this was documented but apparently not...  anything that subclasses the `SkypeObjs` collection class (`SkypeChats`, `SkypeContacts`) is easiest used when iterated over, which implicitly calls the batch methods (e.g. `SkypeChats.recent()`).
