### ISSUE TITLE
Is it possible to seek to a certain message in the chat stream by ID?

### ISSUE THREAD

**Issue by dpovey** [Terrance/SkPy#97]
Hi, 

I was writing a quick tool to download text chat messages, I was able to retrieve back about 30 days by repeatedly calling getMsgs on the chat object - eventually is just returns None.  Is there any way to go further back?  Is it possible to seek to a specific message by id or date?

I had a quick look at the code and the request does seem to take a startTime field which is currently being set to zero, but it wasn't clear to me if this could be leveraged usefully.

**Comment by OllieTerrance** [comment]
30 days is as far back as Skype for Web will go -- as we're piggybacking on their APIs, we can only do as much as the API implements.

`SkypeChat.getMsgs()` is currently hard-coded to go from the top, and remember the position on subsequent messages.  I would assume that if set then it'll return any messages before that time; hopefully it wouldn't require an exact timestamp, but would be inclusive if you used one.

**Comment by Terrance** [comment]
This has since been implemented in #129, following Skype for Web adding support for longer message history.
